# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "409541047b7c32e629c4c494d6e8f168"
name = "North Borders Loyalty [DEV]"
application_url = "https://nbl-dev.app-handler.com"
embedded = true
handle = "north-borders-loyalty-dev"

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "orders/paid" ]
  uri = "/webhooks/app/orders_paid"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "customers/create" ]
  uri = "/webhooks/app/customers_create"

  [[webhooks.subscriptions]]
  topics = [ "customers/delete" ]
  uri = "/webhooks/app/customers_delete"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "customer_read_own_subscription_contracts,read_customers,read_discounts,read_files,read_orders,read_own_subscription_contracts,read_products,write_customers,write_discounts,write_files,write_products"

[auth]
redirect_urls = [ "https://nbl-dev.app-handler.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true
