# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "eb72a94a6c6763364b4aae0941572662"
name = "NB Loyalty & Referral"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_discounts,read_orders,read_products,write_customers,write_discounts,write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true
