# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "409541047b7c32e629c4c494d6e8f168"
name = "NB Loyalty & Referral"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "customers/create" ]
  uri = "/webhooks/app/customers_create"

  [[webhooks.subscriptions]]
  topics = [ "customers/delete" ]
  uri = "/webhooks/app/customers_delete"

  [[webhooks.subscriptions]]
  topics = [ "orders/paid" ]
  uri = "/webhooks/app/orders_paid"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_products,read_orders,read_discounts,write_discounts,write_products,write_customers,customer_read_own_subscription_contracts,read_own_subscription_contracts"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

# app toml