// Auto-generated by StyleManager — do not edit manually.
export const stylePresets = {
    "actionButton": {
        "Color": "#FFFFFD",
        "Margin": "0px 0px 0px 0px",
        "Padding": "10px 20px 10px 20px",
        "Font Size": "14px",
        "Box Shadow": "0 4px 12px rgba(78,203,168,0.35)",
        "Font Weight": "600",
        "Border Color": "#4ECBA8",
        "Border Style": "solid",
        "Border Radius": "9999px",
        "Background Color": "#4ECBA8"
    },
    "header": {
        "Color": "#FFFFFF",
        "Padding": "20px",
        "Font Size": "20px",
        "Font Weight": "700",
        "Background Color": "#4ECBA8"
    },
    "tabHome": {
        "Color": "#1A1A1A",
        "Padding": "16px",
        "Font Size": "14px",
        "Font Weight": "400",
        "Background Color": "#862727",
        "navigation": {
            "Color": "#1A1A1A",
            "Margin": "0px 0px 16px 0px",
            "Padding": "16px 0px 16px 0px",
            "Font Size": "14px",
            "Font Weight": "400",
            "Background Color": "#FFFFFF"
        },
        "activeRewards": {
            "Color": "#FFFFFF",
            "Margin": "0px 0px 16px 0px",
            "Padding": "16px 0px 16px 0px",
            "Font Size": "14px",
            "Font Weight": "400",
            "New Property": "",
            "Background Color": "#4ECBA8"
        },
        "accountActivity": {
            "Color": "#1A1A1A",
            "Margin": "0px 0px 16px 0px",
            "Padding": "16px 0px 16px 0px",
            "Font Size": "14px",
            "Font Weight": "400",
            "Background Color": "#FFFFFF"
        }
    },
    "tabEarnPoints": {
        "Color": "#1A1A1A",
        "Padding": "16px",
        "Font Size": "14px",
        "Font Weight": "400",
        "Background Color": "#FFFFFF"
    },
    "tabRewards": {
        "Color": "#1A1A1A",
        "Padding": "16px",
        "Font Size": "14px",
        "Font Weight": "400",
        "Background Color": "#FFFFFF"
    },
    "tabActivity": {
        "Color": "#1A1A1A",
        "Padding": "16px",
        "Font Size": "13px",
        "Font Weight": "400",
        "Background Color": "#FFFFFF"
    },
    "tabProfile": {
        "Color": "#1A1A1A",
        "Padding": "16px",
        "Font Size": "14px",
        "Font Weight": "400",
        "Background Color": "#FFFFFF"
    },
    "tabReferral": {
        "Color": "#1A1A1A",
        "Padding": "16px",
        "Font Size": "14px",
        "Font Weight": "400",
        "Background Color": "#FFFFFF"
    },
    "accountActivity": {
        "Color": "#1A1A1A",
        "Padding": "16px",
        "Font Size": "14px",
        "Font Weight": "400",
        "Background Color": "#FFFFFF"
    }
};
