// Auto-generated by StyleManager — do not edit manually.
export const stylePresets = {
    "actionButton": {
        "Color": "#FFFFFF",
        "Margin": "0px 0px 0px 0px",
        "Padding": "10px 20px 10px 20px",
        "Font Size": "14px",
        "Box Shadow": "0 4px 12px rgba(78,203,168,0.35)",
        "Font Weight": "600",
        "Border Color": "#4A27BE",
        "Border Style": "solid",
        "Border Radius": "9px",
        "Button Position": "Right",
        "Background Color": "#9648D5"
    },
    "header": {
        "Color": "#FFFFFF",
        "Padding": "20px",
        "Font Size": "20px",
        "Font Weight": "700",
        "Background Color": "#C44BEC",
        "Points": {
            "Color": "#C44BEC",
            "Label": "Account Balance: [points]",
            "Padding": "4px 7px",
            "Font Size": "12px",
            "Border Color": "#EB4747",
            "Border Style": "solid",
            "Border Width": "0px",
            "Border Radius": "15px",
            "Background Color": "white"
        },
        "Heading": {
            "Color": "white",
            "Label": "Welcome, [name]",
            "Margin": "0px 0px 0px 0px",
            "Padding": "0px 0px 0px 0px",
            "Font Size": "18px"
        },
        "Navigation": {
            "Padding": "0px 0px 10px 0px",
            "Font Size": "13px",
            "Font Weight": "300",
            "Active Color": "#C44BEC",
            "Background Color": "#fcfbfb",
            "Active Border Color": "#C44BEC"
        }
    },
    "tabHome": {
        "Color": "#1A1A1A",
        "Padding": "16px",
        "Font Size": "14px",
        "Font Weight": "400",
        "Background Color": "#862727",
        "navigation": {
            "Color": "#1A1A1A",
            "Margin": "0px 0px 9px 0px",
            "Padding": "16px 16px 16px 12px",
            "Font Size": "14px",
            "Font Weight": "400",
            "Background Color": "#8252c7"
        }
    },
    "tabEarnPoints": {
        "Color": "#1A1A1A",
        "Padding": "16px",
        "Font Size": "14px",
        "Font Weight": "400",
        "Background Color": "#FFFFFF"
    },
    "tabRewards": {
        "Color": "#1A1A1A",
        "Padding": "16px",
        "Font Size": "14px",
        "Font Weight": "400",
        "Background Color": "#FFFFFF"
    },
    "tabActivity": {
        "Color": "#1A1A1A",
        "Padding": "16px",
        "Font Size": "13px",
        "Font Weight": "400",
        "Background Color": "#FFFFFF"
    },
    "tabProfile": {
        "Color": "#1A1A1A",
        "Padding": "16px",
        "Font Size": "14px",
        "Font Weight": "400",
        "Background Color": "#FFFFFF"
    },
    "tabReferral": {},
    "accountActivity": {
        "Color": "#1A1A1A",
        "Padding": "16px",
        "Font Size": "14px",
        "Font Weight": "400",
        "Background Color": "#FFFFFF"
    }
};
