// ─────────────────────────────────────────────────────────────────────────────
// constants.js
// Static configuration, design tokens, CSS defaults and utility functions.
// Imported by app_customize.jsx and LivePreview.jsx
// ─────────────────────────────────────────────────────────────────────────────

// ─────────────────────────────────────────────────────────────────────────────
// SIMPLE MODE CONFIG
// ─────────────────────────────────────────────────────────────────────────────

// ─────────────────────────────────────────────────────────────────────────────
// WIDGET CONFIG — Non-CSS behaviour settings
// Saved as styles.widgetConfig in DB, read by applyWidgetConfigOverrides() in JS.
// ─────────────────────────────────────────────────────────────────────────────

export const LABEL_DEFAULTS = {
    // Header
    headerLabel: "Welcome, [name]",
    pointsLabel: "[points] pts",
    // Nav tabs
    navHome: "Home",
    navEarn: "Earn",
    navRewards: "Rewards",
    navMyRewards: "My Rewards",
    navActivity: "Activity",
    // Home nav cards
    homeCardBrowse: "Browse Rewards",
    homeCardEarn: "Earn Points",
    homeCardRefer: "Refer Friends",
    // Section headers
    sectionActiveRewards: "Active Rewards",
    sectionRecentActivity: "Recent Activity",
    // Activity table columns
    activityColDate: "Date",
    activityColActivity: "Activity",
    activityColPoints: "Points",
    // Empty states
    emptyRewards: "No active rewards available",
    emptyActivity: "No account activities yet",
    // Pagination
    loadMoreBtn: "Load More",
    loadMoreDone: "All loaded",
    // Notification
    notifyRewardHeading: "Success! Use this code at checkout",
    notifyRewardCopyBtn: "Copy",
    notifyInfoClaimBtn: "Claim",
    // Launcher
    launcherTitle: "Loyalty Rewards",
    launcherSubtitle: "[points] pts",
    // Prizes
    navPrizes: "Prizes",
    navMyPrizes: "My Prizes",
    sectionPrizeRequests: "My Prize Requests",
    emptyPrizes: "No prizes available",
    emptyMyPrizes: "You have no prize requests yet",
    prizeStatusPending: "🕐 Pending",
    prizeStatusFulfilled: "📦 Fulfilled",
    prizeStatusCompleted: "✅ Completed",
    prizeStatusCancelled: "❌ Cancelled",
    prizeContactUsText: "Contact us",
    prizeClaimSuccessMsg: "✅ Your request has been submitted! We'll contact you soon to arrange delivery.",
    claimingLabel: "Processing...",
    claimRetryLabel: "Try again",
};

export const WIDGET_CONFIG_DEFAULTS = {
    showHomeRewardsSection: true,
    showHomeActivitiesSection: true,
    showHomePrizeRequestsSection: true,
    homeRewardsPerPage: 5,
    homeActivitiesPerPage: 5,
    homePrizeRequestsPerPage: 5,
    myPrizesPerPage: 5,
    paginationMode: "pagination",
    headerEffect: "wave",
    headerEffectOpacity: 0.55,
    headerEffectColorMode: "auto",
    mouseEffect: "bubble",
    mouseEffectIntensity: 0.7,
    labels: { ...LABEL_DEFAULTS },
    prize: {
        showImage: true,
        imageFit: "cover",
        imageHeight: 150,
        imagePosition: "center",
        contactUrl: "",
        showAdminNote: true,
        showTrackingInfo: true,
        showRequestDate: true,
        showFulfilledDate: true,
    },
};

export const WIDGET_CONFIG_SECTIONS = [
    {
        key: "behaviour",
        label: "Behaviour",
        icon: "⚙️",
        description: "Control what sections appear and how content is paged.",
        fields: [
            {
                key: "showHomeRewardsSection",
                label: "Show active rewards on Home tab",
                hint: "Display the 'Active Rewards' section on the Home tab",
                type: "toggle",
                configKey: "showHomeRewardsSection",
                default: true,
            },
            {
                key: "showHomeActivitiesSection",
                label: "Show recent activity on Home tab",
                hint: "Display the 'Recent Activity' section on the Home tab",
                type: "toggle",
                configKey: "showHomeActivitiesSection",
                default: true,
            },
            {
                key: "homeRewardsPerPage",
                label: "Active rewards per page",
                hint: "How many active reward items to show at once on the Home tab",
                type: "range",
                min: 1,
                max: 10,
                unit: "",
                configKey: "homeRewardsPerPage",
                default: 5,
                parseValue: (v) => Number(v),
                displayValue: (v) => Number(v),
            },
            {
                key: "homeActivitiesPerPage",
                label: "Activity rows per page",
                hint: "How many activity rows to show at once on the Home tab",
                type: "range",
                min: 1,
                max: 15,
                unit: "",
                configKey: "homeActivitiesPerPage",
                default: 7,
                parseValue: (v) => Number(v),
                displayValue: (v) => Number(v),
            },
            {
                key: "paginationMode",
                label: "Pagination style",
                hint: "How to load more items in lists — arrow buttons or a Load More button",
                type: "select",
                options: [{ value: "pagination", label: "Arrows" }, { value: "loadmore", label: "Load More button" }],
                configKey: "paginationMode",
                default: "pagination",
            },
            {
                key: "showHomePrizeRequestsSection",
                label: "Show prize requests on Home tab",
                hint: "Display the 'My Prize Requests' section on the Home tab",
                type: "toggle",
                configKey: "showHomePrizeRequestsSection",
                default: true,
            },
            {
                key: "homePrizeRequestsPerPage",
                label: "Prize requests per page (Home)",
                hint: "How many prize request items to show at once on the Home tab",
                type: "range",
                min: 1,
                max: 10,
                unit: "",
                configKey: "homePrizeRequestsPerPage",
                default: 5,
                parseValue: (v) => Number(v),
                displayValue: (v) => Number(v),
            },
            {
                key: "myPrizesPerPage",
                label: "Prize requests per page (My Prizes tab)",
                hint: "How many prize request items to show at once on the My Prizes tab",
                type: "range",
                min: 1,
                max: 20,
                unit: "",
                configKey: "myPrizesPerPage",
                default: 8,
                parseValue: (v) => Number(v),
                displayValue: (v) => Number(v),
            },
        ],
    },
    {
        key: "prizeNotifications",
        label: "Prize Notifications",
        icon: "🏆",
        description: "Control how prize request details appear in the slide-up notification panel.",
        fields: [
            {
                key: "prize_contactUrl",
                label: "Contact page URL",
                hint: "URL shown as a 'Contact us' button on Pending and Cancelled prize notifications. Leave empty to hide the button. E.g. /pages/contact",
                type: "text",
                configKey: "prize.contactUrl",
                default: "",
            },
            {
                key: "prize_showImage",
                label: "Show prize image",
                hint: "Display the prize image (or a placeholder icon) at the top of the notification",
                type: "toggle",
                configKey: "prize.showImage",
                default: true,
            },
            {
                key: "prize_imageFit",
                label: "Image fit",
                hint: "How the image fills the banner area — Cover crops to fill, Contain shows the full image, Auto uses natural height",
                type: "select",
                options: [
                    { value: "cover", label: "Cover (crop to fill)" },
                    { value: "contain", label: "Contain (show full image)" },
                    { value: "auto", label: "Auto (natural height)" },
                ],
                configKey: "prize.imageFit",
                default: "cover",
            },
            {
                key: "prize_imageHeight",
                label: "Image banner height",
                hint: "Height of the image area in pixels (ignored when fit is Auto)",
                type: "range",
                min: 80,
                max: 300,
                unit: "px",
                configKey: "prize.imageHeight",
                default: 150,
                parseValue: (v) => Number(v),
                displayValue: (v) => Number(v),
            },
            {
                key: "prize_imagePosition",
                label: "Image focal point",
                hint: "Which part of the image stays visible when cropped",
                type: "select",
                options: [
                    { value: "center", label: "Center" },
                    { value: "top", label: "Top" },
                    { value: "bottom", label: "Bottom" },
                    { value: "left", label: "Left" },
                    { value: "right", label: "Right" },
                ],
                configKey: "prize.imagePosition",
                default: "center",
            },
            {
                key: "prize_showRequestDate",
                label: "Show request date",
                hint: "Display when the prize was requested in the notification",
                type: "toggle",
                configKey: "prize.showRequestDate",
                default: true,
            },
            {
                key: "prize_showFulfilledDate",
                label: "Show dispatch / completion date",
                hint: "Display when the prize was dispatched or completed in the notification",
                type: "toggle",
                configKey: "prize.showFulfilledDate",
                default: true,
            },
            {
                key: "prize_showAdminNote",
                label: "Show admin note",
                hint: "Display the admin note in the notification (e.g. cancellation reason or delivery details)",
                type: "toggle",
                configKey: "prize.showAdminNote",
                default: true,
            },
            {
                key: "prize_showTrackingInfo",
                label: "Show tracking info",
                hint: "Display tracking link or license key in the notification (shown for Fulfilled and Completed prizes)",
                type: "toggle",
                configKey: "prize.showTrackingInfo",
                default: true,
            },
        ],
    },
    {
        key: "headerAnimation",
        label: "Header Effect",
        icon: "✨",
        description: "Decorative animation displayed in the widget header background.",
        fields: [
            {
                key: "headerEffect",
                label: "Effect style",
                hint: "The visual effect shown in the header",
                type: "select",
                options: [
                    { value: "wave", label: "Wave" },
                    { value: "bubble", label: "Bubble" },
                    { value: "drop", label: "Drop" },
                    { value: "ripple", label: "Ripple" },
                    { value: "none", label: "None" },
                ],
                configKey: "headerEffect",
                default: "wave",
            },
            {
                key: "headerEffectOpacity",
                label: "Effect intensity",
                hint: "How strong the header effect appears (0 = invisible, 100 = full strength)",
                type: "range",
                min: 0,
                max: 100,
                unit: "%",
                configKey: "headerEffectOpacity",
                default: 55,
                parseValue: (v) => Number(v) / 100,
                displayValue: (v) => Math.round(Number(v) * 100),
            },
            {
                key: "headerEffectColorMode",
                label: "Effect color mode",
                hint: "How the effect color is determined — Auto detects from your header color",
                type: "select",
                options: [
                    { value: "auto", label: "Auto (detect from header)" },
                    { value: "light", label: "Light" },
                    { value: "dark", label: "Dark" },
                ],
                configKey: "headerEffectColorMode",
                default: "auto",
            },
        ],
    },
    {
        key: "mouseAnimation",
        label: "Mouse Effect",
        icon: "🖱️",
        description: "Particle effect that follows the cursor inside the open widget.",
        fields: [
            {
                key: "mouseEffect",
                label: "Effect style",
                hint: "The particle effect that follows the mouse cursor",
                type: "select",
                options: [
                    { value: "bubble", label: "Bubble" },
                    { value: "sparkle", label: "Sparkle" },
                    { value: "fire", label: "Fire" },
                    { value: "smoke", label: "Smoke" },
                    { value: "ripple", label: "Ripple" },
                    { value: "none", label: "None" },
                ],
                configKey: "mouseEffect",
                default: "bubble",
            },
            {
                key: "mouseEffectIntensity",
                label: "Effect intensity",
                hint: "How strong the mouse effect appears (0 = barely visible, 100 = full strength)",
                type: "range",
                min: 0,
                max: 100,
                unit: "%",
                configKey: "mouseEffectIntensity",
                default: 70,
                parseValue: (v) => Number(v) / 100,
                displayValue: (v) => Math.round(Number(v) * 100),
            },
        ],
    },
    {
        key: "labels",
        label: "Labels & Text",
        icon: "✏️",
        description: "Customize all text labels shown inside the widget.",
        fields: [
            { key: "lbl_headerLabel", label: "Header greeting", hint: "Use [name] to insert the customer's name. E.g. 'Welcome, [name]'", type: "label", configKey: "labels.headerLabel", default: LABEL_DEFAULTS.headerLabel },
            { key: "lbl_pointsLabel", label: "Points balance text", hint: "Use [points] to insert the balance. E.g. '[points] pts'", type: "label", configKey: "labels.pointsLabel", default: LABEL_DEFAULTS.pointsLabel },
            { key: "lbl_navHome", label: "Nav — Home tab", hint: "Label shown on the Home navigation tab", type: "label", configKey: "labels.navHome", default: LABEL_DEFAULTS.navHome },
            { key: "lbl_navEarn", label: "Nav — Earn tab", hint: "Label shown on the Earn navigation tab", type: "label", configKey: "labels.navEarn", default: LABEL_DEFAULTS.navEarn },
            { key: "lbl_navRewards", label: "Nav — Rewards tab", hint: "Label shown on the Rewards navigation tab", type: "label", configKey: "labels.navRewards", default: LABEL_DEFAULTS.navRewards },
            { key: "lbl_navMyRewards", label: "Nav — My Rewards tab", hint: "Label shown on the My Rewards navigation tab", type: "label", configKey: "labels.navMyRewards", default: LABEL_DEFAULTS.navMyRewards },
            { key: "lbl_navActivity", label: "Nav — Activity tab", hint: "Label shown on the Activity navigation tab", type: "label", configKey: "labels.navActivity", default: LABEL_DEFAULTS.navActivity },
            { key: "lbl_homeCardBrowse", label: "Home card — Browse Rewards", hint: "Text on the Browse Rewards shortcut card on the Home tab", type: "label", configKey: "labels.homeCardBrowse", default: LABEL_DEFAULTS.homeCardBrowse },
            { key: "lbl_homeCardEarn", label: "Home card — Earn Points", hint: "Text on the Earn Points shortcut card on the Home tab", type: "label", configKey: "labels.homeCardEarn", default: LABEL_DEFAULTS.homeCardEarn },
            { key: "lbl_homeCardRefer", label: "Home card — Refer Friends", hint: "Text on the Refer Friends shortcut card on the Home tab", type: "label", configKey: "labels.homeCardRefer", default: LABEL_DEFAULTS.homeCardRefer },
            { key: "lbl_sectionRewards", label: "Section — Active Rewards", hint: "Heading of the Active Rewards section on the Home tab", type: "label", configKey: "labels.sectionActiveRewards", default: LABEL_DEFAULTS.sectionActiveRewards },
            { key: "lbl_sectionActivity", label: "Section — Recent Activity", hint: "Heading of the Recent Activity section on the Home tab", type: "label", configKey: "labels.sectionRecentActivity", default: LABEL_DEFAULTS.sectionRecentActivity },
            { key: "lbl_activityColDate", label: "Activity table — Date", hint: "Column header for the date column in activity tables", type: "label", configKey: "labels.activityColDate", default: LABEL_DEFAULTS.activityColDate },
            { key: "lbl_activityColAct", label: "Activity table — Activity", hint: "Column header for the activity description column", type: "label", configKey: "labels.activityColActivity", default: LABEL_DEFAULTS.activityColActivity },
            { key: "lbl_activityColPts", label: "Activity table — Points", hint: "Column header for the points column in activity tables", type: "label", configKey: "labels.activityColPoints", default: LABEL_DEFAULTS.activityColPoints },
            { key: "lbl_emptyRewards", label: "Empty state — No rewards", hint: "Message shown when there are no active rewards", type: "label", configKey: "labels.emptyRewards", default: LABEL_DEFAULTS.emptyRewards },
            { key: "lbl_emptyActivity", label: "Empty state — No activity", hint: "Message shown when there are no activity entries yet", type: "label", configKey: "labels.emptyActivity", default: LABEL_DEFAULTS.emptyActivity },
            { key: "lbl_loadMoreBtn", label: "Pagination — Load More", hint: "Text on the Load More button", type: "label", configKey: "labels.loadMoreBtn", default: LABEL_DEFAULTS.loadMoreBtn },
            { key: "lbl_loadMoreDone", label: "Pagination — All loaded", hint: "Text shown when all items have been loaded", type: "label", configKey: "labels.loadMoreDone", default: LABEL_DEFAULTS.loadMoreDone },
            { key: "lbl_notifyRewardHead", label: "Reward popup heading", hint: "Heading text inside the reward earned slide-up panel", type: "label", configKey: "labels.notifyRewardHeading", default: LABEL_DEFAULTS.notifyRewardHeading },
            { key: "lbl_notifyRewardCopy", label: "Reward popup copy button", hint: "Text on the Copy button inside the reward popup", type: "label", configKey: "labels.notifyRewardCopyBtn", default: LABEL_DEFAULTS.notifyRewardCopyBtn },
            { key: "lbl_notifyInfoClaim", label: "Info popup claim button", hint: "Text on the action button inside the info slide-up panel", type: "label", configKey: "labels.notifyInfoClaimBtn", default: LABEL_DEFAULTS.notifyInfoClaimBtn },
            { key: "lbl_launcherTitle", label: "Launcher title", hint: "Main title text on the floating launcher button", type: "label", configKey: "labels.launcherTitle", default: LABEL_DEFAULTS.launcherTitle },
            { key: "lbl_launcherSubtitle", label: "Launcher subtitle", hint: "Text shown below the launcher button title. Use [points] for balance. E.g. '[points] pts'", type: "label", configKey: "labels.launcherSubtitle", default: LABEL_DEFAULTS.launcherSubtitle },
            { key: "lbl_navPrizes", label: "Nav — Prizes tab", hint: "Label shown on the Prizes navigation tab", type: "label", configKey: "labels.navPrizes", default: LABEL_DEFAULTS.navPrizes },
            { key: "lbl_navMyPrizes", label: "Nav — My Prizes tab", hint: "Label shown on the My Prizes navigation tab", type: "label", configKey: "labels.navMyPrizes", default: LABEL_DEFAULTS.navMyPrizes },
            { key: "lbl_sectionPrizeRequests", label: "Section — My Prize Requests", hint: "Heading of the Prize Requests section on the Home tab", type: "label", configKey: "labels.sectionPrizeRequests", default: LABEL_DEFAULTS.sectionPrizeRequests },
            { key: "lbl_emptyPrizes", label: "Empty state — No prizes", hint: "Message shown when there are no prizes available", type: "label", configKey: "labels.emptyPrizes", default: LABEL_DEFAULTS.emptyPrizes },
            { key: "lbl_emptyMyPrizes", label: "Empty state — No prize requests", hint: "Message shown when the customer has no prize requests", type: "label", configKey: "labels.emptyMyPrizes", default: LABEL_DEFAULTS.emptyMyPrizes },
            { key: "lbl_prizeStatusPending", label: "Prize status — Pending", hint: "Text shown when a prize request is pending", type: "label", configKey: "labels.prizeStatusPending", default: LABEL_DEFAULTS.prizeStatusPending },
            { key: "lbl_prizeStatusFulfilled", label: "Prize status — Fulfilled", hint: "Text shown when a prize has been dispatched", type: "label", configKey: "labels.prizeStatusFulfilled", default: LABEL_DEFAULTS.prizeStatusFulfilled },
            { key: "lbl_prizeStatusCompleted", label: "Prize status — Completed", hint: "Text shown when a prize has been delivered", type: "label", configKey: "labels.prizeStatusCompleted", default: LABEL_DEFAULTS.prizeStatusCompleted },
            { key: "lbl_prizeStatusCancelled", label: "Prize status — Cancelled", hint: "Text shown when a prize request has been cancelled", type: "label", configKey: "labels.prizeStatusCancelled", default: LABEL_DEFAULTS.prizeStatusCancelled },
            { key: "lbl_prizeContactUsText", label: "Prize — Contact us button", hint: "Label on the Contact us button shown in prize notifications", type: "label", configKey: "labels.prizeContactUsText", default: LABEL_DEFAULTS.prizeContactUsText },
            { key: "lbl_prizeClaimSuccessMsg", label: "Prize — Claim success message", hint: "Message shown after a prize is successfully claimed", type: "label", configKey: "labels.prizeClaimSuccessMsg", default: LABEL_DEFAULTS.prizeClaimSuccessMsg },
            { key: "lbl_claimingLabel", label: "Claim button — Processing", hint: "Text on the claim button while the request is being submitted", type: "label", configKey: "labels.claimingLabel", default: LABEL_DEFAULTS.claimingLabel },
            { key: "lbl_claimRetryLabel", label: "Claim button — Retry", hint: "Text on the claim button after a failed attempt", type: "label", configKey: "labels.claimRetryLabel", default: LABEL_DEFAULTS.claimRetryLabel },
        ],
    },
];

export const SIMPLE_SECTIONS = [
    {
        key: "header",
        label: "Header",
        icon: "📌",
        description: "The coloured strip at the top of the widget — background, text and points badge.",
        fields: [
            { key: "headerBg", label: "Header color", hint: "Background color of the banner at the top of your widget", type: "color", maps: ["--nbl-header-bg"], default: "#8b5cf6" },
            { key: "headerColor", label: "Header title color", hint: "Color of the welcome text shown in the header", type: "color", maps: ["--nbl-header-color"], default: "#ffffff" },
            { key: "headerTitleSize", label: "Title size", hint: "How large the welcome title appears in the header", type: "range", min: 12, max: 22, unit: "px", maps: ["--nbl-header-title-font-size"], default: "16px", parseValue: (v) => `${v}px`, displayValue: (v) => parseInt(v) },
            { key: "pointsBg", label: "Points pill color", hint: "Background color of the points balance pill in the header", type: "color", maps: ["--nbl-points-bg"], default: "rgba(255, 255, 255, 0.2)", resolvedDefault: "#ffffff" },
            { key: "pointsColor", label: "Points pill text", hint: "Color of the number shown inside the points balance pill", type: "color", maps: ["--nbl-points-color"], default: "#ffffff" },
        ],
    },
    {
        key: "navigation",
        label: "Navigation Bar",
        icon: "🗂️",
        description: "The tab bar below the header — background, tab text, active indicator and chevrons.",
        fields: [
            { key: "navBg", label: "Tab bar background", hint: "Background color of the navigation area below the header", type: "color", maps: ["--nbl-nav-bg"], default: "#ffffff" },
            { key: "navBorderColor", label: "Tab bar bottom line", hint: "Color of the divider line below the tab bar", type: "color", maps: ["--nbl-nav-border-color"], default: "#e9e7f0" },
            { key: "navItemColor", label: "Inactive tab color", hint: "Color of tabs that are not currently selected", type: "color", maps: ["--nbl-nav-item-color"], default: "#6b7280" },
            { key: "navActiveColor", label: "Selected tab color", hint: "Color of the currently active tab label and its underline", type: "color", maps: ["--nbl-nav-active-color", "--nbl-nav-active-border"], default: "#8b5cf6" },
            { key: "navChevronColor", label: "Scroll arrow color", hint: "Color of the left/right arrows that appear when there are too many tabs to show", type: "color", maps: ["--nbl-nav-chevron-color"], default: "#6b7280" },
            { key: "navChevronBg", label: "Scroll arrow background", hint: "Background behind the scroll arrows", type: "color", maps: ["--nbl-nav-chevron-bg"], default: "#ffffff" },
            { key: "navItemFontSize", label: "Tab label size", hint: "How large the tab label text appears", type: "range", min: 10, max: 16, unit: "px", maps: ["--nbl-nav-item-font-size"], default: "12px", parseValue: (v) => `${v}px`, displayValue: (v) => parseInt(v) },
        ],
    },
    {
        key: "brand",
        label: "Brand Colors",
        icon: "🎨",
        description: "Primary and accent colors that flow through the whole widget.",
        fields: [
            { key: "primary", label: "Brand primary color", hint: "Your main brand color — used for active tabs and highlights throughout the widget", type: "color", maps: ["--nbl-primary", "--nbl-nav-active-color", "--nbl-nav-active-border", "--nbl-loadmore-color"], default: "#8b5cf6" },
            { key: "accent", label: "Accent color", hint: "Secondary color used for active reward highlights and positive indicators", type: "color", maps: ["--nbl-accent", "--nbl-reward-item-active-border"], default: "#4ecba8" },
        ],
    },
    {
        key: "buttons",
        label: "Action Buttons",
        icon: "🔘",
        description: "The CTA buttons shared across all widget tabs.",
        fields: [
            { key: "btnBg", label: "Button background", hint: "Background color of action buttons like 'Claim Reward'", type: "color", maps: ["--nbl-btn-bg", "--nbl-btn-border"], default: "#4ecba8" },
            { key: "btnColor", label: "Button text color", hint: "Color of the text written on buttons", type: "color", maps: ["--nbl-btn-color"], default: "#ffffff" },
            { key: "btnRadius", label: "Button corner roundness", hint: "How rounded the button corners appear — 0 = sharp, 24 = very rounded", type: "range", min: 0, max: 24, unit: "px", maps: ["--nbl-btn-radius"], default: "10px", parseValue: (v) => `${v}px`, displayValue: (v) => parseInt(v) },
            { key: "btnFontSize", label: "Button text size", hint: "How large the text on buttons appears", type: "range", min: 11, max: 18, unit: "px", maps: ["--nbl-btn-font-size"], default: "14px", parseValue: (v) => `${v}px`, displayValue: (v) => parseInt(v) },
        ],
    },
    {
        key: "text",
        label: "Text & Fonts",
        icon: "✍️",
        description: "Text colors and font size scale used throughout the widget.",
        fields: [
            { key: "textMain", label: "Main text color", hint: "Color for headings, reward names and important labels", type: "color", maps: ["--nbl-text"], default: "#1a1a1a" },
            { key: "textMuted", label: "Subtitle / hint color", hint: "Color for descriptions, dates and secondary information", type: "color", maps: ["--nbl-text-muted"], default: "#6b7280" },
            { key: "textBase", label: "Body text size", hint: "Standard text size used throughout the widget", type: "range", min: 11, max: 16, unit: "px", maps: ["--nbl-text-base"], default: "13px", parseValue: (v) => `${v}px`, displayValue: (v) => parseInt(v) },
            { key: "textLg", label: "Heading text size", hint: "Size of headings and section titles", type: "range", min: 13, max: 22, unit: "px", maps: ["--nbl-text-lg"], default: "16px", parseValue: (v) => `${v}px`, displayValue: (v) => parseInt(v) },
        ],
    },
    {
        key: "surfaces",
        label: "Surfaces & Layout",
        icon: "🪟",
        description: "Widget body background, card backgrounds, borders and border radius.",
        fields: [
            { key: "surface", label: "Widget background", hint: "Main background color of the widget content area", type: "color", maps: ["--nbl-surface"], default: "#ffffff" },
            { key: "surface2", label: "Card background", hint: "Background color for reward cards and section panels", type: "color", maps: ["--nbl-surface-2", "--nbl-reward-item-bg", "--nbl-hsc-header-bg", "--nbl-card-bg"], default: "#f8f7ff" },
            { key: "surfaceHover", label: "Hover highlight", hint: "Background color that appears when hovering over clickable items", type: "color", maps: ["--nbl-surface-hover"], default: "#f3f1fc" },
            { key: "borderColor", label: "Border & divider color", hint: "Color of lines that separate sections and outline cards", type: "color", maps: ["--nbl-border", "--nbl-nav-border-color", "--nbl-card-border", "--nbl-reward-item-border"], default: "#e9e7f0" },
            { key: "radius", label: "Widget corner roundness", hint: "How rounded the outer corners of the widget appear", type: "range", min: 0, max: 28, unit: "px", maps: ["--nbl-radius", "--nbl-radius-xl"], default: "16px", parseValue: (v) => `${v}px`, displayValue: (v) => parseInt(v) },
            { key: "cardRadius", label: "Card corner roundness", hint: "How rounded the corners of cards and rows appear", type: "range", min: 0, max: 20, unit: "px", maps: ["--nbl-card-radius", "--nbl-reward-item-radius", "--nbl-radius-lg"], default: "12px", parseValue: (v) => `${v}px`, displayValue: (v) => parseInt(v) },
            { key: "widgetBodyPadding", label: "Content area spacing", hint: "Inner spacing of the main widget content area", type: "text", maps: ["--nbl-widget-body-padding"], default: "14px 14px 24px" },
        ],
    },
    {
        key: "rewards",
        label: "Reward Items",
        icon: "🎁",
        description: "Cards shown in the Rewards and Active Rewards tabs.",
        fields: [
            { key: "rewardItemBg", label: "Reward card background", hint: "Background color of each reward item card", type: "color", maps: ["--nbl-reward-item-bg"], default: "#f8f7ff" },
            { key: "rewardItemActiveBg", label: "Redeemed card background", hint: "Background color of a reward card that has been claimed or is active", type: "color", maps: ["--nbl-reward-item-active-bg"], default: "#f0fdf9" },
            { key: "rewardItemActiveBorder", label: "Redeemed card border", hint: "Border color highlighting a claimed or active reward card", type: "color", maps: ["--nbl-reward-item-active-border"], default: "#4ecba8" },
            { key: "rewardTitleFontSize", label: "Reward name size", hint: "How large the reward title text appears on each card", type: "range", min: 11, max: 17, unit: "px", maps: ["--nbl-reward-title-font-size"], default: "13.5px", parseValue: (v) => `${v}px`, displayValue: (v) => parseInt(v) },
        ],
    },
    {
        key: "activity",
        label: "Activity Table",
        icon: "📊",
        description: "Points history rows — dividers, earned/spent colors and typography.",
        fields: [
            { key: "activityBorderColor", label: "Row separator color", hint: "Color of the thin line between activity history rows", type: "color", maps: ["--nbl-activity-border-color"], default: "rgba(0,0,0,0.04)" },
            { key: "activityPositive", label: "Points earned color", hint: "Color of the '+' number shown when points are added to the account", type: "color", maps: ["--nbl-activity-positive-color"], default: "#16a34a" },
            { key: "activityNegative", label: "Points spent color", hint: "Color of the '−' number shown when points are used", type: "color", maps: ["--nbl-activity-negative-color"], default: "#dc2626" },
            { key: "activityRowFontSize", label: "Row text size", hint: "How large the text in each activity history row appears", type: "range", min: 10, max: 15, unit: "px", maps: ["--nbl-activity-row-font-size"], default: "12px", parseValue: (v) => `${v}px`, displayValue: (v) => parseInt(v) },
        ],
    },
    {
        key: "pagination",
        label: "Pagination",
        icon: "📄",
        description: "Arrow buttons, dot indicators and the Load More button.",
        fields: [
            { key: "paginationBtnBg", label: "Navigation arrow background", hint: "Background color of the previous/next arrow buttons", type: "color", maps: ["--nbl-pagination-btn-bg"], default: "#ffffff" },
            { key: "paginationBtnColor", label: "Navigation arrow color", hint: "Color of the arrow icon inside the prev/next buttons", type: "color", maps: ["--nbl-pagination-btn-color"], default: "#6b7280" },
            { key: "paginationBtnRadius", label: "Navigation arrow roundness", hint: "How rounded the corners of navigation arrow buttons appear", type: "range", min: 0, max: 20, unit: "px", maps: ["--nbl-pagination-btn-radius"], default: "10px", parseValue: (v) => `${v}px`, displayValue: (v) => parseInt(v) },
            { key: "loadmoreBg", label: "'Load More' button background", hint: "Background color of the Load More button at the bottom of lists", type: "color", maps: ["--nbl-loadmore-bg"], default: "#ffffff" },
            { key: "loadmoreColor", label: "'Load More' text color", hint: "Color of the text on the Load More button", type: "color", maps: ["--nbl-loadmore-color"], default: "#8b5cf6" },
            { key: "loadmoreRadius", label: "'Load More' corner roundness", hint: "How rounded the corners of the Load More button appear", type: "range", min: 0, max: 20, unit: "px", maps: ["--nbl-loadmore-radius"], default: "12px", parseValue: (v) => `${v}px`, displayValue: (v) => parseInt(v) },
        ],
    },
    {
        key: "notifications",
        label: "Notifications",
        icon: "🔔",
        description: "Slide-up panels — reward earned (green) and generic info (dark).",
        fields: [
            { key: "notifyBgFrom", label: "Popup gradient — top color", hint: "First gradient color shared by both reward and info slide-up panels", type: "color", maps: ["--nbl-notify-bg-from"], default: "#15803d" },
            { key: "notifyBgTo", label: "Popup gradient — bottom color", hint: "Second gradient color shared by both reward and info slide-up panels", type: "color", maps: ["--nbl-notify-bg-to"], default: "#22c55e" },
            { key: "notifyColor", label: "Popup text color", hint: "Color of text inside both reward and info slide-up panels", type: "color", maps: ["--nbl-notify-color"], default: "#ffffff" },
            { key: "notifyRewardCodeBg", label: "Reward code box color", hint: "Background color of the code display box inside the reward popup", type: "color", maps: ["--nbl-notify-reward-code-bg"], default: "rgba(255,255,255,0.22)", resolvedDefault: "#b0e8d4" },
            { key: "notifyRewardBtnBg", label: "Reward button background", hint: "Background color of the Copy button inside the reward popup", type: "color", maps: ["--nbl-notify-reward-btn-bg"], default: "#4ecba8" },
            { key: "notifyRewardBtnColor", label: "Reward button text color", hint: "Text color of the Copy button inside the reward popup", type: "color", maps: ["--nbl-notify-reward-btn-color"], default: "#16a34a" },
            { key: "notifyRewardBtnBorder", label: "Reward button border", hint: "Border color of the Copy button inside the reward popup", type: "color", maps: ["--nbl-notify-reward-btn-border"], default: "#4ecba8" },
            { key: "notifyInfoBtnBg", label: "Info button background", hint: "Background color of the action button inside the info popup", type: "color", maps: ["--nbl-notify-info-btn-bg"], default: "#4ecba8" },
            { key: "notifyInfoBtnColor", label: "Info button text color", hint: "Text color of the action button inside the info popup", type: "color", maps: ["--nbl-notify-info-btn-color"], default: "#ffffff" },
            { key: "notifyInfoBtnBorder", label: "Info button border", hint: "Border color of the action button inside the info popup", type: "color", maps: ["--nbl-notify-info-btn-border"], default: "#4ecba8" },
        ],
    },
    {
        key: "status",
        label: "Status Colors",
        icon: "🚦",
        description: "Semantic success / error / warning / info tints used in alerts and badges.",
        fields: [
            { key: "statusSuccessBg", label: "Success highlight color", hint: "Background color used in success messages and badges", type: "color", maps: ["--nbl-status-success-bg"], default: "#f0fdf4" },
            { key: "statusSuccessColor", label: "Success text color", hint: "Color of text inside success messages", type: "color", maps: ["--nbl-status-success-color", "--nbl-status-success-text"], default: "#166534" },
            { key: "statusErrorBg", label: "Error highlight color", hint: "Background color used in error messages", type: "color", maps: ["--nbl-status-error-bg"], default: "#fef2f2" },
            { key: "statusErrorColor", label: "Error text color", hint: "Color of text inside error messages", type: "color", maps: ["--nbl-status-error-color"], default: "#b91c1c" },
            { key: "statusWarningBg", label: "Warning highlight color", hint: "Background color used in warning messages", type: "color", maps: ["--nbl-status-warning-bg"], default: "#fffbeb" },
            { key: "statusWarningColor", label: "Warning text color", hint: "Color of text inside warning messages", type: "color", maps: ["--nbl-status-warning-color", "--nbl-status-warning-strong"], default: "#854d0e" },
            { key: "statusInfoBg", label: "Info highlight color", hint: "Background color used in informational badges", type: "color", maps: ["--nbl-status-info-bg"], default: "#eff6ff" },
            { key: "statusInfoColor", label: "Info text color", hint: "Color of text inside informational messages", type: "color", maps: ["--nbl-status-info-color"], default: "#1e40af" },
        ],
    },
    {
        key: "modal",
        label: "Referral Modal",
        icon: "🔗",
        description: "The referral flow modal that overlays the widget.",
        fields: [
            { key: "modalBg", label: "Popup background", hint: "Background color of the referral invite popup", type: "color", maps: ["--nbl-modal-bg"], default: "#ffffff" },
            { key: "modalRadius", label: "Popup corner roundness", hint: "How rounded the corners of the popup appear", type: "range", min: 0, max: 28, unit: "px", maps: ["--nbl-modal-radius"], default: "20px", parseValue: (v) => `${v}px`, displayValue: (v) => parseInt(v) },
            { key: "modalPadding", label: "Popup inner spacing", hint: "Padding inside the popup content area", type: "text", maps: ["--nbl-modal-padding"], default: "24px 22px 22px" },
            { key: "modalTitleColor", label: "Popup title color", hint: "Color of the large heading text in the popup", type: "color", maps: ["--nbl-modal-title-color"], default: "#111827" },
            { key: "modalTextColor", label: "Popup body text", hint: "Color of the regular paragraph text in the popup", type: "color", maps: ["--nbl-modal-text-color"], default: "#374151" },
            { key: "modalMutedColor", label: "Popup hint text color", hint: "Color of smaller secondary text in the popup", type: "color", maps: ["--nbl-modal-muted-color"], default: "#9ca3af" },
            { key: "modalInputBg", label: "Text field background", hint: "Background color of input boxes inside the popup", type: "color", maps: ["--nbl-modal-input-bg"], default: "#f9fafb" },
            { key: "modalInputBorder", label: "Text field border", hint: "Border color around input boxes", type: "color", maps: ["--nbl-modal-input-border"], default: "#e5e7eb" },
            { key: "modalInputFocus", label: "Text field focus color", hint: "Border color that appears when clicking into an input box", type: "color", maps: ["--nbl-modal-input-focus"], default: "#16a34a" },
            { key: "modalBtnBg", label: "Popup button color", hint: "Background color of the main action button in the popup", type: "color", maps: ["--nbl-modal-btn-primary-bg"], default: "#111827" },
            { key: "modalCodeBg", label: "Referral code box color", hint: "Background color of the box that displays the referral link", type: "color", maps: ["--nbl-modal-code-bg"], default: "#f8fafc" },
            { key: "modalCodeBorder", label: "Referral code box border", hint: "Border color around the referral link box", type: "color", maps: ["--nbl-modal-code-border"], default: "#d1d5db" },
            { key: "modalBrandBg", label: "App badge background", hint: "Background color of the app name badge at the top of the popup", type: "color", maps: ["--nbl-modal-brand-bg"], default: "#ecfdf5" },
            { key: "modalBrandColor", label: "App badge text color", hint: "Color of the text inside the app name badge", type: "color", maps: ["--nbl-modal-brand-color"], default: "#15803d" },
        ],
    },
    {
        key: "launcher",
        label: "Launcher Button",
        icon: "🚀",
        description: "The floating pill on your storefront that opens the widget.",
        fields: [
            { key: "launcherIcon", label: "Button icon", hint: "Emoji icon displayed on the floating button", type: "emoji", options: ["🎁", "⭐", "🏆", "💎", "🎯", "✨", "🎪", "🎀"], maps: ["--nbl-launcher-icon"], default: "'🎁'", displayValue: (v) => v.replace(/^'|'$/g, ""), parseValue: (v) => `'${v}'` },
            { key: "launcherBg", label: "Button background", hint: "Background color of the floating button on your storefront", type: "color", maps: ["--nbl-launcher-bg"], default: "var(--nbl-btn-bg)", resolvedDefault: "#4ecba8" },
            { key: "launcherColor", label: "Button text color", hint: "Color of the text and subtitle on the floating button", type: "color", maps: ["--nbl-launcher-color"], default: "var(--nbl-btn-color)", resolvedDefault: "#ffffff" },
            { key: "launcherRadius", label: "Button shape", hint: "Shape of the floating launcher button", type: "select", options: [{ value: "999px", label: "Pill (default)" }, { value: "16px", label: "Rounded" }, { value: "8px", label: "Slightly rounded" }, { value: "0px", label: "Square" }], maps: ["--nbl-launcher-border-radius"], default: "999px" },
            { key: "launcherPosition", label: "Button position", hint: "Which side of the screen the launcher appears on", type: "select", options: [{ value: "left", label: "Left" }, { value: "right", label: "Right" }], maps: ["--nbl-launcher-position"], default: "right" },
            { key: "launcherBottom", label: "Distance from bottom", hint: "How far from the bottom edge of the screen the button sits", type: "text", maps: ["--nbl-launcher-bottom"], default: "24px" },
            { key: "launcherSideOffset", label: "Side offset", hint: "How far from the left or right edge of the screen the button sits", type: "text", maps: ["--nbl-launcher-side-offset"], default: "20px" },
            { key: "launcherTitleSize", label: "Button text size", hint: "How large the text on the floating button appears", type: "range", min: 10, max: 18, unit: "px", maps: ["--nbl-launcher-title-size"], default: "13px", parseValue: (v) => `${v}px`, displayValue: (v) => parseInt(v) },
        ],
    },
    {
        key: "animations",
        label: "Animations",
        icon: "⚡",
        description: "Speed controls, header decoration effect, and mouse cursor effect.",
        fields: [
            { key: "durFast", label: "Quick animation speed", hint: "Speed of hover and badge transitions", type: "range", min: 50, max: 500, unit: "ms", maps: ["--nbl-dur-fast", "--nbl-transition-fast"], default: "0.18s", parseValue: (v) => `${(v / 1000).toFixed(2)}s`, displayValue: (v) => { const n = parseFloat(v); return Math.round((isNaN(n) ? 0.18 : n) * 1000); } },
            { key: "durNormal", label: "Normal animation speed", hint: "Speed of tab switching and card transitions", type: "range", min: 50, max: 600, unit: "ms", maps: ["--nbl-dur-normal", "--nbl-transition-base"], default: "0.28s", parseValue: (v) => `${(v / 1000).toFixed(2)}s`, displayValue: (v) => { const n = parseFloat(v); return Math.round((isNaN(n) ? 0.28 : n) * 1000); } },
            { key: "durSlow", label: "Slow animation speed", hint: "Speed of the widget opening and closing", type: "range", min: 100, max: 800, unit: "ms", maps: ["--nbl-dur-slow", "--nbl-transition-slow"], default: "0.42s", parseValue: (v) => `${(v / 1000).toFixed(2)}s`, displayValue: (v) => { const n = parseFloat(v); return Math.round((isNaN(n) ? 0.42 : n) * 1000); } },
            { key: "easeSpring", label: "Open animation style", hint: "How the widget feels when it opens", type: "select", options: [{ value: "cubic-bezier(0.34, 1.56, 0.64, 1)", label: "Springy (default)" }, { value: "cubic-bezier(0.22, 1, 0.36, 1)", label: "Smooth" }, { value: "cubic-bezier(0.4, 0, 0.2, 1)", label: "Snappy" }, { value: "linear", label: "Linear" }], maps: ["--nbl-ease-spring"], default: "cubic-bezier(0.34, 1.56, 0.64, 1)" },
            { key: "easeOut", label: "Close animation style", hint: "How the widget feels when it closes", type: "select", options: [{ value: "cubic-bezier(0.22, 1, 0.36, 1)", label: "Smooth (default)" }, { value: "cubic-bezier(0.4, 0, 0.2, 1)", label: "Snappy" }, { value: "cubic-bezier(0.34, 1.56, 0.64, 1)", label: "Springy" }, { value: "linear", label: "Linear" }], maps: ["--nbl-ease-out"], default: "cubic-bezier(0.22, 1, 0.36, 1)" },
        ],
    },
    {
        key: "glow",
        label: "Widget Glow Effect",
        icon: "✨",
        description: "Ambient glow ring around the open widget container.",
        fields: [
            { key: "glowPrimary", label: "Primary glow strength", hint: "How strong the inner glow around the widget appears", type: "range", min: 0, max: 30, unit: "%", maps: ["--nbl-widget-glow-primary"], default: "color-mix(in srgb, var(--nbl-primary) 12%, transparent)", parseValue: (v) => `color-mix(in srgb, var(--nbl-primary) ${v}%, transparent)`, displayValue: (v) => { const m = String(v).match(/(\d+)%/); return m ? parseInt(m[1]) : 12; } },
            { key: "glowHalo", label: "Halo glow strength", hint: "How strong the outer soft halo glow appears", type: "range", min: 0, max: 20, unit: "%", maps: ["--nbl-widget-glow-halo"], default: "color-mix(in srgb, var(--nbl-primary) 5%, transparent)", parseValue: (v) => `color-mix(in srgb, var(--nbl-primary) ${v}%, transparent)`, displayValue: (v) => { const m = String(v).match(/(\d+)%/); return m ? parseInt(m[1]) : 5; } },
        ],
    },
    {
        key: "borders",
        label: "Borders",
        icon: "⬜",
        description: "Color and thickness of dividers and outlines throughout the widget.",
        fields: [
            { key: "borderColor2", label: "Border color", hint: "Color used for all dividers and outline borders", type: "color", maps: ["--nbl-border"], default: "#e9e7f0" },
            { key: "borderWidth", label: "Border thickness", hint: "Thickness of thin dividers and outlines", type: "range", min: 0, max: 4, unit: "px", maps: ["--nbl-border-width"], default: "1px", parseValue: (v) => `${v}px`, displayValue: (v) => parseInt(v) },
            { key: "borderWidthMd", label: "Medium border thickness", hint: "Thickness of slightly heavier outlines", type: "range", min: 0, max: 4, unit: "px", maps: ["--nbl-border-width-md"], default: "1.5px", parseValue: (v) => `${v}px`, displayValue: (v) => parseFloat(v) },
        ],
    },
    {
        key: "borderRadius",
        label: "Border Radius",
        icon: "🔲",
        description: "Corner rounding scale used across the whole widget — from small chips to fully rounded pills.",
        fields: [
            { key: "radiusBase", label: "Base corner radius", hint: "Default rounding for most elements", type: "range", min: 0, max: 20, unit: "px", maps: ["--nbl-radius"], default: "16px", parseValue: (v) => `${v}px`, displayValue: (v) => parseInt(v) },
            { key: "radiusSm", label: "Small corner radius", hint: "Rounding for small elements like tags and badges", type: "range", min: 0, max: 12, unit: "px", maps: ["--nbl-radius-sm"], default: "6px", parseValue: (v) => `${v}px`, displayValue: (v) => parseInt(v) },
            { key: "radiusMd", label: "Medium corner radius", hint: "Rounding for medium UI elements like inputs", type: "range", min: 0, max: 16, unit: "px", maps: ["--nbl-radius-md"], default: "8px", parseValue: (v) => `${v}px`, displayValue: (v) => parseInt(v) },
            { key: "radiusLg", label: "Large corner radius", hint: "Rounding for cards and panels", type: "range", min: 0, max: 24, unit: "px", maps: ["--nbl-radius-lg"], default: "12px", parseValue: (v) => `${v}px`, displayValue: (v) => parseInt(v) },
            { key: "radiusXl", label: "Extra-large corner radius", hint: "Rounding for the main widget container", type: "range", min: 0, max: 32, unit: "px", maps: ["--nbl-radius-xl"], default: "16px", parseValue: (v) => `${v}px`, displayValue: (v) => parseInt(v) },

        ],
    },
    {
        key: "shadows",
        label: "Shadows",
        icon: "🌑",
        description: "Drop shadows for the widget container, cards and navigation chevrons.",
        fields: [
            { key: "shadowWidget", label: "Widget shadow", hint: "How strong the shadow under the widget appears", type: "select", options: [{ value: "none", label: "None" }, { value: "0 4px 16px rgba(0,0,0,0.08)", label: "Subtle" }, { value: "0 8px 40px rgba(0,0,0,0.13)", label: "Medium (default)" }, { value: "0 20px 60px rgba(0,0,0,0.22)", label: "Strong" }], maps: ["--nbl-shadow"], default: "0 8px 40px rgba(0,0,0,0.13)" },
            { key: "shadowSm", label: "Small element shadow", hint: "Shadow on small elevated elements like badges", type: "select", options: [{ value: "none", label: "None" }, { value: "0 1px 4px rgba(0,0,0,0.08)", label: "Subtle (default)" }, { value: "0 2px 8px rgba(0,0,0,0.12)", label: "Medium" }], maps: ["--nbl-shadow-sm"], default: "0 1px 4px rgba(0,0,0,0.08)" },
            { key: "shadowMd", label: "Card shadow", hint: "Shadow on cards and panel menus", type: "select", options: [{ value: "none", label: "None" }, { value: "0 2px 8px rgba(0,0,0,0.06)", label: "Subtle" }, { value: "0 4px 16px rgba(0,0,0,0.10)", label: "Medium (default)" }, { value: "0 8px 24px rgba(0,0,0,0.16)", label: "Strong" }], maps: ["--nbl-shadow-md"], default: "0 4px 16px rgba(0,0,0,0.10)" },
            { key: "shadowChevron", label: "Scroll arrow shadow", hint: "Shadow on the navigation scroll arrows", type: "select", options: [{ value: "none", label: "None" }, { value: "0 2px 8px rgba(0,0,0,0.12)", label: "Subtle (default)" }, { value: "0 4px 12px rgba(0,0,0,0.18)", label: "Medium" }], maps: ["--nbl-shadow-nav-chevron"], default: "0 2px 8px rgba(0,0,0,0.12)" },
        ],
    },
    {
        key: "cards",
        label: "Cards & Sections",
        icon: "🃏",
        description: "Shared styling for every card-style container in the widget.",
        fields: [
            { key: "cardBg", label: "Card background", hint: "Background color of cards and content sections", type: "color", maps: ["--nbl-card-bg"], default: "#ffffff" },
            { key: "cardBorder", label: "Card border color", hint: "Color of the border around cards", type: "color", maps: ["--nbl-card-border"], default: "#e9e7f0" },
            { key: "cardRadius2", label: "Card corner radius", hint: "How rounded the corners of cards are", type: "range", min: 0, max: 24, unit: "px", maps: ["--nbl-card-radius"], default: "12px", parseValue: (v) => `${v}px`, displayValue: (v) => parseInt(v) },
            { key: "cardPadding", label: "Card inner spacing", hint: "Padding inside cards (e.g. 16px)", type: "text", maps: ["--nbl-card-padding"], default: "16px" },
            { key: "cardShadow", label: "Card shadow", hint: "Drop shadow on reward and content cards", type: "select", options: [{ value: "none", label: "None (default)" }, { value: "0 2px 8px rgba(0,0,0,0.06)", label: "Subtle" }, { value: "0 4px 16px rgba(0,0,0,0.10)", label: "Medium" }], maps: ["--nbl-card-shadow"], default: "none" },
        ],
    },
    {
        key: "homeSectionCards",
        label: "Home Section Headers",
        icon: "🏠",
        description: "The header strip shown above Active Rewards and Activity lists on the Home tab.",
        fields: [
            { key: "hscHeaderBg", label: "Section header background", hint: "Background of the section header strip on the Home tab", type: "color", maps: ["--nbl-hsc-header-bg"], default: "#f8f7ff" },
            { key: "hscHeaderPadding", label: "Section header padding", hint: "Inner spacing of the section header strip", type: "text", maps: ["--nbl-hsc-header-padding"], default: "10px 14px" },
            { key: "hscHeaderRadius", label: "Section header radius", hint: "Corner rounding of the section header strip", type: "range", min: 0, max: 20, unit: "px", maps: ["--nbl-hsc-header-radius"], default: "10px", parseValue: (v) => `${v}px`, displayValue: (v) => parseInt(v) },
            { key: "hscTitleFontSize", label: "Section title size", hint: "Font size of the section heading text", type: "range", min: 10, max: 16, unit: "px", maps: ["--nbl-hsc-title-font-size"], default: "12px", parseValue: (v) => `${v}px`, displayValue: (v) => parseInt(v) },
            { key: "hscTitleColor", label: "Section title color", hint: "Color of the section heading text", type: "color", maps: ["--nbl-hsc-title-color"], default: "#6b7280" },
            { key: "homeNavColor", label: "Home nav card text color", hint: "Text color on the navigation shortcut cards on the Home tab", type: "color", maps: ["--nbl-home-nav-color"], default: "#1a1a2e" },
        ],
    },
];

// ─────────────────────────────────────────────────────────────────────────────
// PRESET THEMES — Comprehensive with Light / Dark / Accent / Neon / etc.
// ─────────────────────────────────────────────────────────────────────────────

export const PRESETS = [
    {
        key: "violet",
        label: "Violet Dream",
        emoji: "💜",
        swatches: ["#7c3aed", "#a78bfa", "#ede9fe"],
        tagline: "Rich purple tones",
        vars: {
            "--nbl-primary": "#7c3aed", "--nbl-header-bg": "#7c3aed",
            "--nbl-nav-active-color": "#7c3aed", "--nbl-nav-active-border": "#7c3aed",
            "--nbl-loadmore-color": "#7c3aed", "--nbl-accent": "#a78bfa",
            "--nbl-btn-bg": "#7c3aed", "--nbl-btn-border": "#7c3aed", "--nbl-btn-color": "#ffffff",
            "--nbl-reward-item-active-border": "#a78bfa", "--nbl-reward-item-active-bg": "#f5f3ff",
            "--nbl-launcher-bg": "#7c3aed",
            "--nbl-surface": "#ffffff", "--nbl-surface-2": "#f5f3ff",
            "--nbl-reward-item-bg": "#f5f3ff", "--nbl-hsc-header-bg": "#f5f3ff",
            "--nbl-nav-bg": "#ffffff", "--nbl-nav-item-color": "#6b7280",
            "--nbl-text": "#1a1a2e", "--nbl-text-muted": "#6b7280",
            "--nbl-border": "#ede9fe", "--nbl-nav-border-color": "#ede9fe",
            "--nbl-card-bg": "#ffffff", "--nbl-card-border": "#ede9fe",
            "--nbl-notify-bg-from": "#4c1d95", "--nbl-notify-bg-to": "#7c3aed",
            "--nbl-notify-color": "#ffffff",
            "--nbl-notify-reward-code-bg": "rgba(255,255,255,0.18)",
            "--nbl-notify-reward-btn-bg": "#a78bfa", "--nbl-notify-reward-btn-color": "#3b0764", "--nbl-notify-reward-btn-border": "#a78bfa",
            "--nbl-notify-info-btn-bg": "#a78bfa", "--nbl-notify-info-btn-color": "#3b0764", "--nbl-notify-info-btn-border": "#a78bfa",
        },
    },
    {
        key: "midnight",
        label: "Midnight Dark",
        emoji: "🌙",
        swatches: ["#6366f1", "#818cf8", "#1e1b4b"],
        tagline: "Sleek dark mode",
        vars: {
            "--nbl-primary": "#4338ca", "--nbl-header-bg": "#1e1b4b",
            "--nbl-nav-active-color": "#818cf8", "--nbl-nav-active-border": "#818cf8",
            "--nbl-loadmore-color": "#818cf8", "--nbl-accent": "#6366f1",
            "--nbl-btn-bg": "#6366f1", "--nbl-btn-border": "#6366f1", "--nbl-btn-color": "#ffffff",
            "--nbl-reward-item-active-border": "#818cf8", "--nbl-reward-item-active-bg": "#1e1b4b",
            "--nbl-launcher-bg": "#6366f1",
            "--nbl-surface": "#0f0e1a", "--nbl-surface-2": "#1a1833",
            "--nbl-reward-item-bg": "#1a1833", "--nbl-hsc-header-bg": "#1a1833",
            "--nbl-nav-bg": "#12111f", "--nbl-nav-item-color": "#a5b4fc",
            "--nbl-text": "#e0e7ff", "--nbl-text-muted": "#a5b4fc",
            "--nbl-border": "#2d2b52", "--nbl-nav-border-color": "#2d2b52",
            "--nbl-card-bg": "#1a1833", "--nbl-card-border": "#2d2b52",
            "--nbl-home-nav-color": "#e0e7ff",
            "--nbl-notify-bg-from": "#3730a3", "--nbl-notify-bg-to": "#6366f1",
            "--nbl-notify-color": "#ffffff",
            "--nbl-notify-reward-code-bg": "rgba(255,255,255,0.18)",
            "--nbl-notify-reward-btn-bg": "#818cf8", "--nbl-notify-reward-btn-color": "#1e1b4b", "--nbl-notify-reward-btn-border": "#818cf8",
            "--nbl-notify-info-btn-bg": "#818cf8", "--nbl-notify-info-btn-color": "#1e1b4b", "--nbl-notify-info-btn-border": "#818cf8",
        },
    },
    {
        key: "emerald",
        label: "Emerald Forest",
        emoji: "🌿",
        swatches: ["#059669", "#34d399", "#ecfdf5"],
        tagline: "Fresh & natural",
        vars: {
            "--nbl-primary": "#059669", "--nbl-header-bg": "#059669",
            "--nbl-nav-active-color": "#059669", "--nbl-nav-active-border": "#059669",
            "--nbl-loadmore-color": "#059669", "--nbl-accent": "#34d399",
            "--nbl-btn-bg": "#059669", "--nbl-btn-border": "#059669", "--nbl-btn-color": "#ffffff",
            "--nbl-reward-item-active-border": "#34d399", "--nbl-reward-item-active-bg": "#ecfdf5",
            "--nbl-launcher-bg": "#059669",
            "--nbl-surface": "#ffffff", "--nbl-surface-2": "#ecfdf5",
            "--nbl-reward-item-bg": "#ecfdf5", "--nbl-hsc-header-bg": "#ecfdf5",
            "--nbl-nav-bg": "#ffffff", "--nbl-nav-item-color": "#6b7280",
            "--nbl-text": "#0a1f18", "--nbl-text-muted": "#6b7280",
            "--nbl-border": "#a7f3d0", "--nbl-nav-border-color": "#a7f3d0",
            "--nbl-card-bg": "#ffffff", "--nbl-card-border": "#a7f3d0",
            "--nbl-notify-bg-from": "#065f46", "--nbl-notify-bg-to": "#059669",
            "--nbl-notify-color": "#ffffff",
            "--nbl-notify-reward-code-bg": "rgba(255,255,255,0.2)",
            "--nbl-notify-reward-btn-bg": "#34d399", "--nbl-notify-reward-btn-color": "#064e3b", "--nbl-notify-reward-btn-border": "#34d399",
            "--nbl-notify-info-btn-bg": "#34d399", "--nbl-notify-info-btn-color": "#064e3b", "--nbl-notify-info-btn-border": "#34d399",
        },
    },
    {
        key: "ocean",
        label: "Ocean Breeze",
        emoji: "🌊",
        swatches: ["#0284c7", "#38bdf8", "#f0f9ff"],
        tagline: "Cool & professional",
        vars: {
            "--nbl-primary": "#0284c7", "--nbl-header-bg": "#0284c7",
            "--nbl-nav-active-color": "#0284c7", "--nbl-nav-active-border": "#0284c7",
            "--nbl-loadmore-color": "#0284c7", "--nbl-accent": "#38bdf8",
            "--nbl-btn-bg": "#0284c7", "--nbl-btn-border": "#0284c7", "--nbl-btn-color": "#ffffff",
            "--nbl-reward-item-active-border": "#38bdf8", "--nbl-reward-item-active-bg": "#f0f9ff",
            "--nbl-launcher-bg": "#0284c7",
            "--nbl-surface": "#ffffff", "--nbl-surface-2": "#f0f9ff",
            "--nbl-reward-item-bg": "#f0f9ff", "--nbl-hsc-header-bg": "#f0f9ff",
            "--nbl-nav-bg": "#ffffff", "--nbl-nav-item-color": "#6b7280",
            "--nbl-text": "#0c1a2e", "--nbl-text-muted": "#6b7280",
            "--nbl-border": "#bae6fd", "--nbl-nav-border-color": "#bae6fd",
            "--nbl-card-bg": "#ffffff", "--nbl-card-border": "#bae6fd",
            "--nbl-notify-bg-from": "#075985", "--nbl-notify-bg-to": "#0284c7",
            "--nbl-notify-color": "#ffffff",
            "--nbl-notify-reward-code-bg": "rgba(255,255,255,0.2)",
            "--nbl-notify-reward-btn-bg": "#38bdf8", "--nbl-notify-reward-btn-color": "#0c4a6e", "--nbl-notify-reward-btn-border": "#38bdf8",
            "--nbl-notify-info-btn-bg": "#38bdf8", "--nbl-notify-info-btn-color": "#0c4a6e", "--nbl-notify-info-btn-border": "#38bdf8",
        },
    },
    {
        key: "blush",
        label: "Blush Pink",
        emoji: "🌸",
        swatches: ["#db2777", "#f472b6", "#fdf2f8"],
        tagline: "Soft & feminine",
        vars: {
            "--nbl-primary": "#db2777", "--nbl-header-bg": "#db2777",
            "--nbl-nav-active-color": "#db2777", "--nbl-nav-active-border": "#db2777",
            "--nbl-loadmore-color": "#db2777", "--nbl-accent": "#f472b6",
            "--nbl-btn-bg": "#db2777", "--nbl-btn-border": "#db2777", "--nbl-btn-color": "#ffffff",
            "--nbl-reward-item-active-border": "#f472b6", "--nbl-reward-item-active-bg": "#fdf2f8",
            "--nbl-launcher-bg": "#db2777",
            "--nbl-surface": "#ffffff", "--nbl-surface-2": "#fdf2f8",
            "--nbl-reward-item-bg": "#fdf2f8", "--nbl-hsc-header-bg": "#fdf2f8",
            "--nbl-nav-bg": "#ffffff", "--nbl-nav-item-color": "#9d174d",
            "--nbl-text": "#1a0011", "--nbl-text-muted": "#9d174d",
            "--nbl-border": "#fce7f3", "--nbl-nav-border-color": "#fce7f3",
            "--nbl-card-bg": "#ffffff", "--nbl-card-border": "#fce7f3",
            "--nbl-notify-bg-from": "#9d174d", "--nbl-notify-bg-to": "#db2777",
            "--nbl-notify-color": "#ffffff",
            "--nbl-notify-reward-code-bg": "rgba(255,255,255,0.2)",
            "--nbl-notify-reward-btn-bg": "#f472b6", "--nbl-notify-reward-btn-color": "#831843", "--nbl-notify-reward-btn-border": "#f472b6",
            "--nbl-notify-info-btn-bg": "#f472b6", "--nbl-notify-info-btn-color": "#831843", "--nbl-notify-info-btn-border": "#f472b6",
        },
    },
];



// ─────────────────────────────────────────────────────────────────────────────
// DEFAULT VALUES
// ─────────────────────────────────────────────────────────────────────────────

export const CSS_DEFAULTS = {
    "--nbl-primary": "#8b5cf6",
    "--nbl-primary-hover": "color-mix(in srgb, var(--nbl-primary) 85%, #000)",
    "--nbl-primary-light": "color-mix(in srgb, var(--nbl-primary) 12%, #fff)",
    "--nbl-accent": "#4ecba8",
    "--nbl-accent-hover": "color-mix(in srgb, var(--nbl-accent) 85%, #000)",
    "--nbl-accent-light": "color-mix(in srgb, var(--nbl-accent) 12%, #fff)",
    "--nbl-header-bg": "#8b5cf6",
    "--nbl-header-color": "#ffffff",
    "--nbl-header-padding": "22px 20px 18px",
    "--nbl-header-compact-padding": "10px 20px",
    "--nbl-header-title-font-size": "16px",
    "--nbl-header-title-font-weight": "700",
    "--nbl-points-bg": "rgba(255, 255, 255, 0.2)",
    "--nbl-points-color": "#ffffff",
    "--nbl-points-font-size": "12px",
    "--nbl-points-padding": "5px 12px",
    "--nbl-points-border-radius": "99px",
    "--nbl-points-border-color": "rgba(255, 255, 255, 0.22)",
    "--nbl-nav-bg": "#ffffff",
    "--nbl-nav-border-color": "#e9e7f0",
    "--nbl-nav-padding": "0 12px",
    "--nbl-nav-active-color": "#8b5cf6",
    "--nbl-nav-active-border": "#8b5cf6",
    "--nbl-nav-item-color": "#6b7280",
    "--nbl-nav-item-font-size": "12px",
    "--nbl-nav-item-font-weight": "500",
    "--nbl-nav-item-active-font-weight": "600",
    "--nbl-nav-item-padding": "14px 4px 12px",
    "--nbl-nav-item-border-width": "2.5px",
    "--nbl-nav-chevron-color": "#6b7280",
    "--nbl-nav-chevron-hover-color": "#8b5cf6",
    "--nbl-nav-chevron-bg": "#ffffff",
    "--nbl-nav-chevron-border": "#e9e7f0",
    "--nbl-nav-chevron-size": "28px",
    "--nbl-nav-chevron-icon-size": "14px",
    "--nbl-nav-chevron-radius": "8px",
    "--nbl-btn-bg": "#4ecba8",
    "--nbl-btn-color": "#ffffff",
    "--nbl-btn-border": "#4ecba8",
    "--nbl-btn-radius": "10px",
    "--nbl-btn-font-size": "14px",
    "--nbl-btn-font-weight": "600",
    "--nbl-btn-padding": "10px 20px",
    "--nbl-btn-hover-filter": "brightness(1.07)",
    "--nbl-surface": "#ffffff",
    "--nbl-surface-2": "#f8f7ff",
    "--nbl-surface-hover": "#f3f1fc",
    "--nbl-text": "#1a1a1a",
    "--nbl-text-muted": "#6b7280",
    "--nbl-text-xs": "11px",
    "--nbl-text-sm": "12px",
    "--nbl-text-base": "13px",
    "--nbl-text-md": "13.5px",
    "--nbl-text-lg": "16px",
    "--nbl-border": "#e9e7f0",
    "--nbl-border-width": "1px",
    "--nbl-border-width-md": "1.5px",
    "--nbl-radius": "16px",
    "--nbl-radius-sm": "8px",
    "--nbl-radius-md": "10px",
    "--nbl-radius-lg": "12px",
    "--nbl-radius-xl": "16px",
    "--nbl-radius-full": "999px",
    "--nbl-shadow": "0 20px 60px rgba(0,0,0,0.18), 0 4px 16px rgba(0,0,0,0.08)",
    "--nbl-shadow-sm": "0 2px 8px rgba(0,0,0,0.06), inset 0 1px 0 rgba(255,255,255,0.9)",
    "--nbl-shadow-md": "0 6px 20px rgba(0,0,0,0.12)",
    "--nbl-shadow-nav-chevron": "0 2px 8px rgba(0,0,0,0.1)",
    "--nbl-card-bg": "#ffffff",
    "--nbl-card-border": "#e9e7f0",
    "--nbl-card-radius": "12px",
    "--nbl-card-padding": "14px 13px",
    "--nbl-card-shadow": "0 2px 12px rgba(0,0,0,0.06)",
    "--nbl-hsc-header-bg": "#f8f7ff",
    "--nbl-hsc-header-padding": "10px 14px",
    "--nbl-hsc-header-radius": "10px 10px 0 0",
    "--nbl-hsc-title-font-size": "13px",
    "--nbl-hsc-title-font-weight": "600",
    "--nbl-hsc-title-color": "#1a1a1a",
    "--nbl-hsc-icon-size": "16px",
    "--nbl-home-nav-color": "#ffffff",
    "--nbl-reward-item-bg": "#f8f7ff",
    "--nbl-reward-item-border": "#e9e7f0",
    "--nbl-reward-item-active-bg": "#f0fdf9",
    "--nbl-reward-item-active-border": "#4ecba8",
    "--nbl-reward-item-radius": "12px",
    "--nbl-reward-item-padding": "14px 13px",
    "--nbl-reward-title-font-size": "13.5px",
    "--nbl-reward-title-font-weight": "600",
    "--nbl-reward-points-font-size": "12px",
    "--nbl-reward-item-hover-shadow": "0 6px 18px rgba(78,203,168,0.25)",
    "--nbl-activity-header-font-size": "10px",
    "--nbl-activity-header-font-weight": "700",
    "--nbl-activity-row-font-size": "12px",
    "--nbl-activity-row-padding": "7px 4px",
    "--nbl-activity-border-color": "rgba(0,0,0,0.04)",
    "--nbl-activity-positive-color": "#16a34a",
    "--nbl-activity-negative-color": "#dc2626",
    "--nbl-pagination-btn-size": "32px",
    "--nbl-pagination-btn-radius": "10px",
    "--nbl-pagination-btn-border": "#e9e7f0",
    "--nbl-pagination-btn-bg": "#ffffff",
    "--nbl-pagination-btn-color": "#6b7280",
    "--nbl-pagination-dot-size": "7px",
    "--nbl-pagination-dot-active-width": "18px",
    "--nbl-pagination-dot-radius": "4px",
    "--nbl-loadmore-radius": "12px",
    "--nbl-loadmore-border": "#e9e7f0",
    "--nbl-loadmore-bg": "#ffffff",
    "--nbl-loadmore-color": "#8b5cf6",
    "--nbl-loadmore-font-size": "13px",
    "--nbl-loadmore-font-weight": "600",
    "--nbl-loadmore-padding": "11px 20px",
    "--nbl-notify-bg-from": "#15803d",
    "--nbl-notify-bg-to": "#22c55e",
    "--nbl-notify-color": "#ffffff",
    "--nbl-notify-reward-code-bg": "rgba(255,255,255,0.22)",
    "--nbl-notify-reward-btn-bg": "#4ecba8",
    "--nbl-notify-reward-btn-color": "#16a34a",
    "--nbl-notify-reward-btn-border": "#4ecba8",
    "--nbl-notify-info-btn-bg": "#4ecba8",
    "--nbl-notify-info-btn-color": "#ffffff",
    "--nbl-notify-info-btn-border": "#4ecba8",
    "--nbl-status-success-bg": "#f0fdf4",
    "--nbl-status-success-border": "#86efac",
    "--nbl-status-success-color": "#166534",
    "--nbl-status-success-text": "#15803d",
    "--nbl-status-error-bg": "#fef2f2",
    "--nbl-status-error-border": "#fecaca",
    "--nbl-status-error-color": "#b91c1c",
    "--nbl-status-warning-bg": "#fffbeb",
    "--nbl-status-warning-border": "#fcd34d",
    "--nbl-status-warning-color": "#854d0e",
    "--nbl-status-warning-strong": "#b45309",
    "--nbl-status-info-bg": "#eff6ff",
    "--nbl-status-info-border": "#bfdbfe",
    "--nbl-status-info-color": "#1e40af",
    "--nbl-modal-bg": "#ffffff",
    "--nbl-modal-title-color": "#111827",
    "--nbl-modal-subtitle-color": "#4b5563",
    "--nbl-modal-text-color": "#374151",
    "--nbl-modal-muted-color": "#9ca3af",
    "--nbl-modal-brand-bg": "#ecfdf5",
    "--nbl-modal-brand-color": "#15803d",
    "--nbl-modal-input-bg": "#f9fafb",
    "--nbl-modal-input-border": "#e5e7eb",
    "--nbl-modal-input-focus": "#16a34a",
    "--nbl-modal-input-readonly": "#f3f4f6",
    "--nbl-modal-btn-primary-bg": "#111827",
    "--nbl-modal-btn-primary-hover": "#1f2937",
    "--nbl-modal-code-bg": "#f8fafc",
    "--nbl-modal-code-border": "#d1d5db",
    "--nbl-modal-code-hover-bg": "#f0fdf4",
    "--nbl-modal-code-hover-border": "#16a34a",
    "--nbl-modal-scrollbar-color": "#d1d5db",
    "--nbl-ease-spring": "cubic-bezier(0.34, 1.56, 0.64, 1)",
    "--nbl-ease-out": "cubic-bezier(0.22, 1, 0.36, 1)",
    "--nbl-transition-fast": "0.15s",
    "--nbl-transition-base": "0.22s",
    "--nbl-transition-slow": "0.35s",
    "--nbl-launcher-bg": "var(--nbl-btn-bg)",
    "--nbl-launcher-color": "var(--nbl-btn-color)",
    "--nbl-launcher-border-radius": "999px",
    "--nbl-launcher-size": "50px",
    "--nbl-launcher-radius": "999px",
    "--nbl-launcher-elevation": "0 6px 24px rgba(0, 0, 0, 0.22)",
    "--nbl-launcher-shadow": "0 6px 24px rgba(0,0,0,0.22), 0 2px 8px rgba(0,0,0,0.14), 0 0 0 3px rgba(255,255,255,0.15) inset",
    "--nbl-launcher-shadow-hover": "0 14px 36px rgba(0,0,0,0.28), 0 4px 12px rgba(0,0,0,0.18), 0 0 0 3px rgba(255,255,255,0.15) inset",
    "--nbl-launcher-shadow-float": "0 14px 32px rgba(0,0,0,0.28), 0 4px 10px rgba(0,0,0,0.16), 0 0 0 3px rgba(255,255,255,0.15) inset",
    "--nbl-launcher-icon": "'🎁'",
    "--nbl-launcher-icon-size": "20px",
    "--nbl-launcher-icon-bg": "rgba(0,0,0,0.18)",
    "--nbl-launcher-icon-circle": "44px",
    "--nbl-launcher-title-size": "13px",
    "--nbl-launcher-title-weight": "700",
    "--nbl-launcher-sub-size": "11px",
    "--nbl-launcher-sub-weight": "500",
    "--nbl-launcher-sub-opacity": "0.82",
    "--nbl-launcher-shimmer-color": "rgba(255,255,255,0.28)",
    "--nbl-launcher-bottom": "24px",
    "--nbl-launcher-position": "right",
    "--nbl-launcher-side-offset": "20px",
    "--nbl-widget-body-padding": "14px 14px 24px",
    "--nbl-modal-radius": "20px",
    "--nbl-modal-padding": "24px 22px 22px",
    "--nbl-dur-fast": "0.18s",
    "--nbl-dur-normal": "0.28s",
    "--nbl-dur-slow": "0.42s",
    "--nbl-pg-btn-size": "30px",
    "--nbl-pg-btn-radius": "8px",
    "--nbl-header-effect": "wave",
    "--nbl-header-effect-opacity": "55%",
    "--nbl-mouse-effect": "bubble",
    "--nbl-mouse-effect-intensity": "70%",
    "--nbl-widget-glow-primary": "color-mix(in srgb, var(--nbl-primary) 12%, transparent)",
    "--nbl-widget-glow-halo": "color-mix(in srgb, var(--nbl-primary) 5%, transparent)",
};

// ─────────────────────────────────────────────────────────────────────────────
// HELPERS
// ─────────────────────────────────────────────────────────────────────────────

export function deepClone(obj) { return JSON.parse(JSON.stringify(obj)); }
export function isEqual(a, b) { return JSON.stringify(a) === JSON.stringify(b); }
export function buildInitialVars(savedCssVars) {
    const base = deepClone(CSS_DEFAULTS);
    if (!savedCssVars || typeof savedCssVars !== "object") return base;
    return { ...base, ...savedCssVars };
}

export function buildInitialWidgetConfig(saved) {
    const base = { ...WIDGET_CONFIG_DEFAULTS, labels: { ...LABEL_DEFAULTS }, prize: { ...WIDGET_CONFIG_DEFAULTS.prize } };
    if (!saved || typeof saved !== "object") return base;
    const merged = { ...base, ...saved };
    // Deep merge labels and prize so partial saves don't lose defaults
    merged.labels = { ...LABEL_DEFAULTS, ...(saved.labels || {}) };
    merged.prize = { ...WIDGET_CONFIG_DEFAULTS.prize, ...(saved.prize || {}) };
    return merged;
}
export const HEX_RE = /^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/;
export function isHex(v) { return HEX_RE.test((v ?? "").trim()); }

// ─────────────────────────────────────────────────────────────────────────────
// INLINE STYLES (design system)
// ─────────────────────────────────────────────────────────────────────────────

export const DS = {
    sp2: "2px", sp4: "4px", sp6: "6px", sp8: "8px", sp10: "10px", sp12: "12px",
    sp14: "14px", sp16: "16px", sp20: "20px", sp24: "24px",
    r6: "6px", r8: "8px", r10: "10px", r12: "12px", r14: "14px", r16: "16px", r99: "99px",
    white: "#ffffff",
    bg: "#f9fafb",
    bgCard: "#ffffff",
    borderLight: "#e5e7eb",
    borderMid: "#d1d5db",
    text: "#111827",
    textSub: "#374151",
    textMuted: "#6b7280",
    textHint: "#9ca3af",
    accentBg: "#f5f3ff",
    accentText: "#6d28d9",
    accentBorder: "#ede9fe",
    warnBg: "#fffbeb",
    warnBorder: "#fde68a",
    warnText: "#92400e",
    dangerText: "#dc2626",
    dangerBg: "#fef2f2",
};

// ─────────────────────────────────────────────────────────────────────────────
// SECTION → SCENE MAP
// Maps every CSS group key and simple section key to a preview "scene" so that
// clicking a group in the sidebar automatically shows the relevant widget view.
// ─────────────────────────────────────────────────────────────────────────────

export const SECTION_TO_SCENE = {
    // ── Simple mode section keys (SIMPLE_SECTIONS[].key) ─────────────────
    header: "home",             // Header bg, text, points badge
    navigation: "home",             // Nav bar tabs, chevrons
    brand: "home",             // Primary + accent colors
    buttons: "earn",             // Action CTA buttons shown in Earn tab
    text: "home",             // Text & fonts
    surfaces: "home",             // Surfaces, borders, radius
    rewards: "rewards",          // Reward item cards
    activity: "home",             // Activity table
    pagination: "rewards",          // Load More + arrow buttons
    notifications: "notification-reward", // Reward + info slide-up panels
    status: "home",             // Status color tints
    modal: "modal",              // Referral modal — standalone preview, no widget
    animations: "home",             // Transition durations / easing
    glow: "home",             // Widget glow ring

};