import { stylePresets } from "../presets/stylePresets";
import { useState, useEffect, useRef } from "react";
import prisma from "db-server";
import { authenticate } from "shopify-server";
import { useActionData, useLoaderData, useSubmit, useNavigation } from "react-router";
import syncAppConfig from "../controller/metafieldsSync/syncAppConfig";


// ── Loader ────────────────────────────────────────────────────────────────────

export const loader = async ({ request }) => {
    const { session } = await authenticate.admin(request);

    const style = await prisma.style.findUnique({
        where: { shop: session.shop },
    });

    const STYLE_KEYS = Object.keys(stylePresets);

    // Build schema from DB if it exists, otherwise fall back to stylePresets.
    const base = style ?? stylePresets;
    const schema = {};
    for (const key of STYLE_KEYS) {
        schema[key] = base[key] ?? stylePresets[key] ?? {};
    }

    // Detect mismatch: keys or fields in DB that are not in stylePresets (or vice versa).
    let syncWarning = null;
    if (style) {
        const dbKeys = Object.keys(style).filter((k) => STYLE_KEYS.includes(k));
        const missingInDb = STYLE_KEYS.filter((k) => !(k in style) || style[k] === null);
        const extraInDb = dbKeys.filter((k) => {
            const dbTab = style[k];
            const presetTab = stylePresets[k];
            if (!presetTab || !dbTab) return false;
            // Check if DB tab has fields not present in preset.
            const dbFields = Object.keys(dbTab);
            const presetFields = Object.keys(presetTab);
            const extra = dbFields.filter((f) => !(f in presetTab));
            const missing = presetFields.filter((f) => !(f in dbTab));
            return extra.length > 0 || missing.length > 0;
        });

        if (missingInDb.length > 0 || extraInDb.length > 0) {
            syncWarning = {
                missingInDb,
                mismatchedTabs: extraInDb,
            };
        }
    }

    return { schema, syncWarning };
};


// ── Action ────────────────────────────────────────────────────────────────────

export const action = async ({ request }) => {
    const { session, admin } = await authenticate.admin(request);
    const formData = await request.formData();
    const intent = formData.get("intent");

    if (intent === "save") {
        const raw = formData.get("schema");

        // Parse error — malformed JSON from client.
        let schema;
        try {
            schema = JSON.parse(raw);
        } catch (err) {
            return {
                ok: false,
                errorType: "parse",
                message: "Failed to parse schema data.",
                detail: err.message,
            };
        }

        // DB save error.
        try {
            await prisma.style.upsert({
                where: { shop: session.shop },
                update: schema,
                create: { shop: session.shop, sessionId: session.id, ...schema },
            });
        } catch (err) {
            console.error("[StyleManager] DB upsert failed:", err);
            return {
                ok: false,
                errorType: "db",
                message: "Failed to save to database.",
                detail: err.message,
            };
        }

        // Preset file sync — non-fatal, DB save already succeeded.
        let presetSynced = true;
        let presetError = null;
        try {
            const { writeFile } = await import("fs/promises");
            const { resolve } = await import("path");
            const presetsPath = resolve("app/presets/stylePresets.js");
            const fileContent = `// Auto-generated by StyleManager — do not edit manually.\nexport const stylePresets = ${JSON.stringify(schema, null, 4)};\n`;
            await writeFile(presetsPath, fileContent, "utf8");
        } catch (err) {
            console.error("[StyleManager] Failed to write stylePresets.js:", err);
            presetSynced = false;
            presetError = err.message;
        }

        await syncAppConfig(admin, session);

        return {
            ok: true,
            savedSchema: schema,
            message: presetSynced
                ? "Schema saved and presets updated."
                : "Schema saved. Preset file sync failed — check server logs.",
            presetError: presetError ?? null,
        };
    }

    return {
        ok: false,
        errorType: "unknown_intent",
        message: `Unknown intent: "${intent}".`,
        detail: null,
    };
};


// ── Constants ─────────────────────────────────────────────────────────────────

const STYLE_KEYS = Object.keys(stylePresets);

const STYLE_KEY_LABELS = {
    actionButton: "Action Button",
    header: "Header",
    tabHome: "Home Tab",
    tabEarnPoints: "Earn Points Tab",
    tabRewards: "Rewards Tab",
    tabActivity: "Activity Tab",
    tabProfile: "Profile Tab",
    tabReferral: "Referral Tab",
    accountActivity: "Account Activity",
};

// Stable modal IDs for commandFor wiring.
const FIELD_MODAL_ID = "confirm-remove-field-modal";
const GROUP_MODAL_ID = "confirm-remove-group-modal";


// ── Helpers ───────────────────────────────────────────────────────────────────

function isGroup(value) {
    return typeof value === "object" && value !== null;
}

function deepClone(obj) {
    return JSON.parse(JSON.stringify(obj));
}

function isEqual(a, b) {
    return JSON.stringify(a) === JSON.stringify(b);
}

// Centralized toast helper.
// duration defaults: success=3000, error=5000, info/warning=3000
function toast(message, { isError = false, duration } = {}) {
    const defaultDuration = isError ? 5000 : 3000;
    shopify.toast.show(message, {
        isError,
        duration: duration ?? defaultDuration,
    });
}

let _idCounter = 0;
function newId() {
    return `fid_${++_idCounter}`;
}

function toRows(obj) {
    return Object.entries(obj)
        .filter(([, v]) => !isGroup(v))
        .map(([key, value]) => ({ id: newId(), key, value }));
}

function toGroupRows(obj) {
    return Object.entries(obj)
        .filter(([, v]) => isGroup(v))
        .map(([key, groupObj]) => ({
            id: newId(),
            key,
            rows: toRows(groupObj),
        }));
}

function rowsToObject(flatRows, groupRows) {
    const result = {};
    for (const { key, value } of flatRows) {
        result[key] = value;
    }
    for (const { key, rows } of groupRows) {
        const group = {};
        for (const { key: fk, value: fv } of rows) {
            group[fk] = fv;
        }
        result[key] = group;
    }
    return result;
}

function uniquePlaceholder(rows, base = "New Property") {
    const existing = new Set(rows.map((r) => r.key));
    let key = base;
    let i = 1;
    while (existing.has(key)) {
        key = `${base} ${i}`;
        i++;
    }
    return key;
}

function uniqueGroupPlaceholder(groupRows, base = "newGroup") {
    const existing = new Set(groupRows.map((g) => g.key));
    let key = base;
    let i = 1;
    while (existing.has(key)) {
        key = `${base}${i}`;
        i++;
    }
    return key;
}


// ── FieldRow ──────────────────────────────────────────────────────────────────

function FieldRow({ row, onKeyChange, onValueChange, onRemoveClick }) {
    return (
        <s-grid gridTemplateColumns="1fr 1fr auto" gap="small">
            <s-text-field
                label="Property"
                label-hidden
                placeholder="e.g. Font Size"
                value={row.key}
                onInput={(e) => onKeyChange(e.target.value)}
                auto-complete="off"
            />
            <s-text-field
                label="Value"
                label-hidden
                placeholder="e.g. 14px"
                value={row.value}
                onInput={(e) => onValueChange(e.target.value)}
                auto-complete="off"
            />
            <s-box>
                <s-box paddingBlockEnd="base" paddingBlockStart="small" />
                <s-button
                    variant="plain"
                    tone="critical"
                    onClick={onRemoveClick}
                >
                    Remove
                </s-button>
            </s-box>
        </s-grid>
    );
}


// ── FlatFieldsSection ─────────────────────────────────────────────────────────

function FlatFieldsSection({ rows, onRowsChange, onPendingFieldChange, onShowFieldModal, activeTabKey }) {
    function handleKeyChange(id, newKey) {
        onRowsChange(rows.map((r) => (r.id === id ? { ...r, key: newKey } : r)));
    }

    function handleValueChange(id, newValue) {
        onRowsChange(rows.map((r) => (r.id === id ? { ...r, value: newValue } : r)));
    }

    function handleAdd() {
        const key = uniquePlaceholder(rows);
        onRowsChange([...rows, { id: newId(), key, value: "" }]);
    }

    return (
        <s-stack direction="vertical" gap="small">
            <s-grid gridTemplateColumns="1fr 1fr auto" gap="small">
                <s-text tone="subdued">Property</s-text>
                <s-text tone="subdued">Value</s-text>
                <s-box />
            </s-grid>

            {rows.length === 0 && (
                <s-text tone="subdued">No fields yet. Add one below.</s-text>
            )}

            {rows.map((row) => (
                <FieldRow
                    key={row.id}
                    row={row}
                    onKeyChange={(v) => handleKeyChange(row.id, v)}
                    onValueChange={(v) => handleValueChange(row.id, v)}
                    // Store the pending row id before the modal opens.
                    onRemoveClick={() => {
                        onPendingFieldChange({ rowId: row.id, rowKey: row.key, rowValue: row.value, groupId: null, tabKey: activeTabKey, groupKey: null });
                        onShowFieldModal();
                    }}
                />
            ))}

            <s-button variant="plain" onClick={handleAdd}>
                + Add field
            </s-button>
        </s-stack>
    );
}


// ── NestedGroupSection ────────────────────────────────────────────────────────

function NestedGroupSection({ group, onGroupKeyChange, onGroupRowsChange, onGroupRemoveClick, onPendingFieldChange, onShowFieldModal, activeTabKey }) {
    function handleFieldKeyChange(id, newKey) {
        onGroupRowsChange(group.rows.map((r) => (r.id === id ? { ...r, key: newKey } : r)));
    }

    function handleFieldValueChange(id, newValue) {
        onGroupRowsChange(group.rows.map((r) => (r.id === id ? { ...r, value: newValue } : r)));
    }

    function handleAddField() {
        const key = uniquePlaceholder(group.rows);
        onGroupRowsChange([...group.rows, { id: newId(), key, value: "" }]);
    }

    return (
        <s-box padding="base" background="bg-surface-secondary" borderRadius="base">
            <s-stack direction="vertical" gap="small">

                <s-grid gridTemplateColumns="1fr auto" gap="small">
                    <s-text-field
                        label="Group name"
                        label-hidden
                        placeholder="e.g. navigation"
                        value={group.key}
                        onInput={(e) => onGroupKeyChange(e.target.value)}
                        auto-complete="off"
                    />
                    <s-box>
                        <s-box paddingBlockEnd="base" paddingBlockStart="small" />
                        <s-button
                            variant="plain"
                            tone="critical"
                            onClick={onGroupRemoveClick}
                        >
                            Remove group
                        </s-button>
                    </s-box>
                </s-grid>

                <s-divider />

                <s-stack direction="vertical" gap="small">
                    <s-grid gridTemplateColumns="1fr 1fr auto" gap="small">
                        <s-text tone="subdued">Property</s-text>
                        <s-text tone="subdued">Value</s-text>
                        <s-box />
                    </s-grid>

                    {group.rows.length === 0 && (
                        <s-text tone="subdued">No fields in this group.</s-text>
                    )}

                    {group.rows.map((row) => (
                        <FieldRow
                            key={row.id}
                            row={row}
                            onKeyChange={(v) => handleFieldKeyChange(row.id, v)}
                            onValueChange={(v) => handleFieldValueChange(row.id, v)}
                            onRemoveClick={() => {
                                onPendingFieldChange({ rowId: row.id, rowKey: row.key, rowValue: row.value, groupId: group.id, tabKey: activeTabKey, groupKey: group.key });
                                onShowFieldModal();
                            }}
                        />
                    ))}

                    <s-button variant="plain" onClick={handleAddField}>
                        + Add field
                    </s-button>
                </s-stack>

            </s-stack>
        </s-box>
    );
}


// ── Page ──────────────────────────────────────────────────────────────────────

function schemaToState(schema) {
    const state = {};
    for (const tabKey of STYLE_KEYS) {
        const tabObj = schema[tabKey] ?? {};
        state[tabKey] = {
            flatRows: toRows(tabObj),
            groupRows: toGroupRows(tabObj),
        };
    }
    return state;
}

function stateToSchema(state) {
    const schema = {};
    for (const tabKey of STYLE_KEYS) {
        const { flatRows, groupRows } = state[tabKey];
        schema[tabKey] = rowsToObject(flatRows, groupRows);
    }
    return schema;
}


export default function StyleManager() {
    const { schema: loadedSchema, syncWarning } = useLoaderData();
    const actionData = useActionData();
    const submit = useSubmit();
    const navigation = useNavigation();

    const isSubmitting = navigation.state === "submitting";

    const [tabState, setTabState] = useState(() => schemaToState(loadedSchema));
    // Keep syncWarning in local state so the user can dismiss it manually.
    const [showSyncWarning, setShowSyncWarning] = useState(!!syncWarning);
    // Initialize savedSchema via stateToSchema so its format always matches currentSchema.
    const [savedSchema, setSavedSchema] = useState(() => stateToSchema(schemaToState(loadedSchema)));
    const [activeTab, setActiveTab] = useState(STYLE_KEYS[0]);

    // deletedItems: array of { type: "field"|"group", tabKey, groupId?, groupKey?, row?, group? }
    // Keeps deleted items so they can be restored individually.
    const [deletedItems, setDeletedItems] = useState([]);

    // restoreModalRef — modal for browsing and restoring deleted items.
    const restoreModalRef = useRef(null);

    // errorBanner: { message, detail } — shown when action returns ok: false.
    const [errorBanner, setErrorBanner] = useState(null);

    // pendingField: { rowId, rowKey, groupId? } — set before modal opens.
    const [pendingField, setPendingField] = useState(null);
    // pendingGroup: { tabKey, groupId, groupKey } — set before modal opens.
    const [pendingGroup, setPendingGroup] = useState(null);

    // Refs to call hideOverlay() after confirming.
    const fieldModalRef = useRef(null);
    const groupModalRef = useRef(null);

    const currentSchema = stateToSchema(tabState);
    const hasChanges = !isEqual(currentSchema, savedSchema);

    useEffect(() => {
        if (!actionData) return;

        if (actionData.ok) {
            setErrorBanner(null);

            if (actionData.savedSchema) {
                setSavedSchema(actionData.savedSchema);
            }

            if (actionData.presetError) {
                // DB saved but preset file sync failed — non-fatal warning.
                toast("Saved to DB. Preset file sync failed.", { duration: 5000 });
                setErrorBanner({
                    message: "Preset file sync failed.",
                    detail: actionData.presetError,
                });
            } else {
                toast("Schema saved successfully.");
            }
        } else {
            setErrorBanner({
                message: actionData.message ?? "An unknown error occurred.",
                detail: actionData.detail ?? null,
            });

            // errorType-specific toast messages.
            const errorMessages = {
                parse: "Invalid schema data — could not parse.",
                db: "Database error — changes were not saved.",
                unknown_intent: "Something went wrong — unknown action.",
            };
            const msg = errorMessages[actionData.errorType] ?? actionData.message ?? "An error occurred.";
            toast(msg, { isError: true });
        }
    }, [actionData]);

    // ── Tab state helpers ─────────────────────────────────────────────────────

    function setFlatRows(tabKey, flatRows) {
        setTabState((prev) => ({ ...prev, [tabKey]: { ...prev[tabKey], flatRows } }));
    }

    function setGroupRows(tabKey, groupRows) {
        setTabState((prev) => ({ ...prev, [tabKey]: { ...prev[tabKey], groupRows } }));
    }

    // ── Field removal ─────────────────────────────────────────────────────────

    function handleConfirmFieldRemove() {
        if (!pendingField) return;
        const { rowId, groupId } = pendingField;

        if (groupId) {
            const group = tabState[activeTab].groupRows.find((g) => g.id === groupId);
            const removedRow = group?.rows.find((r) => r.id === rowId);
            if (removedRow) {
                setDeletedItems((prev) => [
                    ...prev,
                    // Store groupKey so the restore modal can show a readable label.
                    { type: "field", tabKey: activeTab, groupId, groupKey: group?.key, row: removedRow },
                ]);
            }
            const newGroupRows = tabState[activeTab].groupRows.map((g) =>
                g.id === groupId ? { ...g, rows: g.rows.filter((r) => r.id !== rowId) } : g
            );
            setGroupRows(activeTab, newGroupRows);
        } else {
            const removedRow = tabState[activeTab].flatRows.find((r) => r.id === rowId);
            if (removedRow) {
                setDeletedItems((prev) => [
                    ...prev,
                    { type: "field", tabKey: activeTab, groupId: null, row: removedRow },
                ]);
            }
            setFlatRows(activeTab, tabState[activeTab].flatRows.filter((r) => r.id !== rowId));
        }

        fieldModalRef.current?.hideOverlay();
        setPendingField(null);
        toast(`"${pendingField.rowKey}" removed. Don't forget to save.`, { duration: 3000 });
    }

    // ── Group removal ─────────────────────────────────────────────────────────

    function handleGroupRemoveRequest(tabKey, groupId, groupKey) {
        setPendingGroup({ tabKey, groupId, groupKey });
        groupModalRef.current?.showOverlay();
    }

    function handleConfirmGroupRemove() {
        if (!pendingGroup) return;
        const { tabKey, groupId } = pendingGroup;

        const removedGroup = tabState[tabKey].groupRows.find((g) => g.id === groupId);
        if (removedGroup) {
            setDeletedItems((prev) => [
                ...prev,
                { type: "group", tabKey, group: deepClone(removedGroup) },
            ]);
        }

        setGroupRows(tabKey, tabState[tabKey].groupRows.filter((g) => g.id !== groupId));
        groupModalRef.current?.hideOverlay();
        const removedKey = pendingGroup.groupKey;
        setPendingGroup(null);
        toast(`Group "${removedKey}" removed. Don't forget to save.`, { duration: 3000 });
    }

    // ── Group key / rows update ───────────────────────────────────────────────

    function handleGroupKeyChange(tabKey, groupId, newKey) {
        setGroupRows(tabKey, tabState[tabKey].groupRows.map((g) =>
            g.id === groupId ? { ...g, key: newKey } : g
        ));
    }

    function handleGroupRowsChange(tabKey, groupId, newRows) {
        setGroupRows(tabKey, tabState[tabKey].groupRows.map((g) =>
            g.id === groupId ? { ...g, rows: newRows } : g
        ));
    }

    function handleAddGroup(tabKey) {
        const { groupRows } = tabState[tabKey];
        const key = uniqueGroupPlaceholder(groupRows);
        setGroupRows(tabKey, [...groupRows, { id: newId(), key, rows: [] }]);
    }

    // ── Restore deleted item ──────────────────────────────────────────────────

    function handleRestoreItem(item, index) {
        if (item.type === "field") {
            if (item.groupId) {
                // Restore field into its group (append at end).
                setTabState((prev) => {
                    const tabS = { ...prev[item.tabKey] };
                    tabS.groupRows = tabS.groupRows.map((g) =>
                        g.id === item.groupId
                            ? { ...g, rows: [...g.rows, { ...item.row, id: newId() }] }
                            : g
                    );
                    return { ...prev, [item.tabKey]: tabS };
                });
            } else {
                // Restore flat field.
                setTabState((prev) => {
                    const tabS = { ...prev[item.tabKey] };
                    tabS.flatRows = [...tabS.flatRows, { ...item.row, id: newId() }];
                    return { ...prev, [item.tabKey]: tabS };
                });
            }
        } else if (item.type === "group") {
            // Restore entire group.
            setTabState((prev) => {
                const tabS = { ...prev[item.tabKey] };
                tabS.groupRows = [...tabS.groupRows, { ...item.group, id: newId() }];
                return { ...prev, [item.tabKey]: tabS };
            });
        }

        // Remove from deleted list.
        setDeletedItems((prev) => prev.filter((_, i) => i !== index));

        const label = item.type === "group"
            ? `Group "${item.group.key}" restored.`
            : `"${item.row.key}" restored.`;
        toast(label, { duration: 2000 });
    }

    // ── Save / Discard ────────────────────────────────────────────────────────

    function handleSave() {
        const formData = new FormData();
        formData.set("intent", "save");
        formData.set("schema", JSON.stringify(currentSchema));
        submit(formData, { method: "post" });
    }

    function handleDiscard() {
        setTabState(schemaToState(savedSchema));
        toast("Changes discarded.", { duration: 2000 });
    }

    // ── Render ────────────────────────────────────────────────────────────────

    const { flatRows, groupRows } = tabState[activeTab];

    return (
        <s-page>

            {/* ── Field remove confirmation modal ── */}
            <s-modal
                id={FIELD_MODAL_ID}
                ref={fieldModalRef}
                heading="Remove field"
                accessibilityLabel="Remove field confirmation"
                size="small"
            >
                <s-stack gap="base">
                    <s-text>Are you sure you want to remove this field?</s-text>
                    <s-stack gap="extraSmall">
                        <s-text tone="subdued">Section</s-text>
                        <s-text type="strong">
                            {STYLE_KEY_LABELS[pendingField?.tabKey] ?? pendingField?.tabKey ?? "—"}
                            {pendingField?.groupKey ? ` › ${pendingField.groupKey}` : ""}
                        </s-text>
                    </s-stack>
                    <s-stack gap="extraSmall">
                        <s-text tone="subdued">Property</s-text>
                        <s-text type="strong">{pendingField?.rowKey || "—"}</s-text>
                    </s-stack>
                    <s-stack gap="extraSmall">
                        <s-text tone="subdued">Value</s-text>
                        <s-text type="strong">{pendingField?.rowValue || "—"}</s-text>
                    </s-stack>
                    <s-text tone="caution">This cannot be undone.</s-text>
                </s-stack>

                <s-button
                    slot="primary-action"
                    variant="primary"
                    tone="critical"
                    onClick={handleConfirmFieldRemove}
                >
                    Remove
                </s-button>
                <s-button
                    slot="secondary-actions"
                    variant="secondary"
                    commandFor={FIELD_MODAL_ID}
                    command="--hide"
                >
                    Cancel
                </s-button>
            </s-modal>

            {/* ── Group remove confirmation modal ── */}
            <s-modal
                id={GROUP_MODAL_ID}
                ref={groupModalRef}
                heading="Remove group"
                accessibilityLabel="Remove group confirmation"
                size="small"
            >
                <s-stack gap="base">
                    <s-text>Are you sure you want to remove this group and all its fields?</s-text>
                    <s-stack gap="extraSmall">
                        <s-text tone="subdued">Section</s-text>
                        <s-text type="strong">{STYLE_KEY_LABELS[pendingGroup?.tabKey] ?? pendingGroup?.tabKey ?? "—"}</s-text>
                    </s-stack>
                    <s-stack gap="extraSmall">
                        <s-text tone="subdued">Group</s-text>
                        <s-text type="strong">{pendingGroup?.groupKey || "—"}</s-text>
                    </s-stack>
                    <s-text tone="caution">This cannot be undone.</s-text>
                </s-stack>

                <s-button
                    slot="primary-action"
                    variant="primary"
                    tone="critical"
                    onClick={handleConfirmGroupRemove}
                >
                    Remove group
                </s-button>
                <s-button
                    slot="secondary-actions"
                    variant="secondary"
                    commandFor={GROUP_MODAL_ID}
                    command="--hide"
                >
                    Cancel
                </s-button>
            </s-modal>

            {/* ── Restore deleted items modal ── */}
            <s-modal
                id="restore-modal"
                ref={restoreModalRef}
                heading="Restore deleted items"
                accessibilityLabel="Restore deleted items"
                size="base"
            >
                {deletedItems.length === 0 ? (
                    <s-text tone="subdued">No deleted items to restore.</s-text>
                ) : (
                    <s-stack direction="vertical" gap="small">
                        {deletedItems.map((item, index) => (
                            <s-box key={index} padding="small" background="bg-surface-secondary" borderRadius="base">
                                <s-stack direction="inline" alignItems="center" justifyContent="space-between" gap="small">
                                    <s-stack direction="vertical" gap="extraSmall">
                                        <s-text type="strong">
                                            {item.type === "group"
                                                ? `Group: ${item.group.key}`
                                                : `Field: ${item.row.key}`}
                                        </s-text>
                                        <s-text tone="subdued">
                                            {STYLE_KEY_LABELS[item.tabKey] ?? item.tabKey}
                                            {item.groupId ? ` › ${item.groupKey ?? item.group?.key ?? "group"}` : ""}
                                        </s-text>
                                        {item.type === "field" && (
                                            <s-text tone="subdued">Value: {item.row.value || "—"}</s-text>
                                        )}
                                    </s-stack>
                                    <s-button
                                        variant="plain"
                                        onClick={() => handleRestoreItem(item, index)}
                                    >
                                        Restore
                                    </s-button>
                                </s-stack>
                            </s-box>
                        ))}
                    </s-stack>
                )}
                <s-button
                    slot="secondary-actions"
                    variant="secondary"
                    commandFor="restore-modal"
                    command="--hide"
                >
                    Close
                </s-button>
            </s-modal>

            {/* ── Top bar ── */}
            <s-section>
                <s-stack direction="inline" alignItems="center" justifyContent="space-between" gap="base">
                    <s-box>
                        <s-heading>Style Schema Editor</s-heading>
                        <s-text tone="subdued">
                            Add, edit, or remove style fields. Changes are synced to the presets file.
                        </s-text>
                    </s-box>
                    <s-stack direction="inline" gap="base" alignItems="center">
                        <s-button
                            variant="plain"
                            onClick={() => restoreModalRef.current?.showOverlay()}
                            disabled={deletedItems.length === 0 || isSubmitting}
                        >
                            Restore deleted ({deletedItems.length})
                        </s-button>
                        <s-button
                            variant="plain"
                            onClick={handleDiscard}
                            disabled={!hasChanges || isSubmitting}
                        >
                            Discard
                        </s-button>
                        <s-button
                            variant="primary"
                            onClick={handleSave}
                            disabled={!hasChanges || isSubmitting}
                            loading={isSubmitting}
                        >
                            Save
                        </s-button>
                    </s-stack>
                </s-stack>
            </s-section>

            {/* ── Error banner ── */}
            {errorBanner && (
                <s-section>
                    <s-banner
                        tone="critical"
                        dismissible
                        onDismiss={() => setErrorBanner(null)}
                    >
                        <s-stack gap="small">
                            <s-text type="strong">{errorBanner.message}</s-text>
                            {errorBanner.detail && (
                                <s-text tone="subdued">{errorBanner.detail}</s-text>
                            )}
                        </s-stack>
                    </s-banner>
                </s-section>
            )}

            {/* ── Sync warning banner ── */}
            {/* Render only when showSyncWarning is true — avoids conflicting with
                s-banner's internal hidden/animation state management. */}
            {syncWarning && showSyncWarning && (
                <s-section>
                    <s-banner
                        tone="warning"
                        dismissible
                        onDismiss={() => setShowSyncWarning(false)}
                    >
                        <s-stack gap="small">
                            <s-text type="strong">DB and preset file are out of sync.</s-text>
                            {syncWarning.missingInDb.length > 0 && (
                                <s-text>
                                    Tabs missing in DB: {syncWarning.missingInDb.join(", ")}
                                </s-text>
                            )}
                            {syncWarning.mismatchedTabs.length > 0 && (
                                <s-text>
                                    Field mismatches in: {syncWarning.mismatchedTabs.map((k) => STYLE_KEY_LABELS[k] ?? k).join(", ")}
                                </s-text>
                            )}
                            <s-text tone="subdued">
                                Save the current schema to sync DB with presets, or edit fields to match.
                            </s-text>
                            <s-box>
                                <s-button
                                    variant="primary"
                                    onClick={handleSave}
                                    disabled={isSubmitting}
                                    loading={isSubmitting}
                                >
                                    Sync now
                                </s-button>
                            </s-box>
                        </s-stack>
                    </s-banner>
                </s-section>
            )}

            {/* ── Two-column layout ── */}
            <s-grid gridTemplateColumns="1fr 3fr" gap="base">

                {/* ── Left: tab nav ── */}
                <s-section>
                    <s-stack gap="small">
                        {STYLE_KEYS.map((key) => (
                            <s-button
                                key={key}
                                variant={activeTab === key ? "primary" : "tertiary"}
                                onClick={() => setActiveTab(key)}
                            >
                                {STYLE_KEY_LABELS[key] ?? key}
                            </s-button>
                        ))}
                    </s-stack>
                </s-section>

                {/* ── Right: editor ── */}
                <s-section>
                    <s-stack direction="vertical" gap="base">

                        {/* Flat fields */}
                        <s-box>
                            <s-box paddingBlockEnd="small">
                                <s-heading as="h2">
                                    {STYLE_KEY_LABELS[activeTab] ?? activeTab} — Fields
                                </s-heading>
                            </s-box>
                            <FlatFieldsSection
                                rows={flatRows}
                                onRowsChange={(rows) => setFlatRows(activeTab, rows)}
                                onPendingFieldChange={setPendingField}
                                onShowFieldModal={() => fieldModalRef.current?.showOverlay()}
                                activeTabKey={activeTab}
                            />
                        </s-box>

                        <s-divider />

                        {/* Nested groups */}
                        <s-box>
                            <s-stack direction="inline" alignItems="center" justifyContent="space-between" gap="base">
                                <s-heading as="h3">Nested Groups</s-heading>
                                <s-button variant="plain" onClick={() => handleAddGroup(activeTab)}>
                                    + Add group
                                </s-button>
                            </s-stack>

                            <s-box paddingBlockStart="small">
                                {groupRows.length === 0 && (
                                    <s-text tone="subdued">
                                        No nested groups. Click "+ Add group" to create one.
                                    </s-text>
                                )}
                                <s-stack direction="vertical" gap="base">
                                    {groupRows.map((group) => (
                                        <NestedGroupSection
                                            key={group.id}
                                            group={group}
                                            onGroupKeyChange={(newKey) =>
                                                handleGroupKeyChange(activeTab, group.id, newKey)
                                            }
                                            onGroupRowsChange={(newRows) =>
                                                handleGroupRowsChange(activeTab, group.id, newRows)
                                            }
                                            onGroupRemoveClick={() =>
                                                handleGroupRemoveRequest(activeTab, group.id, group.key)
                                            }
                                            onPendingFieldChange={setPendingField}
                                            onShowFieldModal={() => fieldModalRef.current?.showOverlay()}
                                            activeTabKey={activeTab}
                                        />
                                    ))}
                                </s-stack>
                            </s-box>
                        </s-box>

                    </s-stack>
                </s-section>

            </s-grid>
        </s-page>
    );
}